create table Trainer
(
    TID          integer not null
        primary key,
    TrainerName  char(16),
    TrainerClass char(16),
    check ("TID" > -1)
);

INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (1, 'Thalia', 'Beauty');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (2, 'Demetrius', 'Youngster');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (3, 'Duncan', 'Sailor');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (4, 'Charlie', 'Tuber');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (5, 'Garrison', 'Ruin Maniac');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (6, 'Jani', 'Tuber');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (7, 'Kira & Dan', 'Young Couple');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (8, 'Sidney', 'Elite Four');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (9, 'Phoebe', 'Elite Four');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (10, 'Glacia', 'Elite Four');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (11, 'Drake', 'Elite Four');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (12, 'Wallace', 'Champion');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (13, 'Calvin', 'Youngster');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (14, 'Rick', 'Bug Catcher');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (15, 'Allen', 'Youngster');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (16, 'Tiana', 'Lass');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (17, 'Brendan', 'Pokemon Trainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (18, 'May', 'Pokemon Trainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (19, 'Isabelle', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (20, 'Pete', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (21, 'Daisy', 'Aroma Lady');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (22, 'Amy & Liv', 'Twins');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (23, 'Miguel', 'Pokefan');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (24, 'Andrew', 'Fisherman');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (25, 'Rhett', 'Black Belt');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (26, 'Marcos', 'Guitarist');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (27, 'Imani', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (28, 'Dominik', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (29, 'Foster', 'Ruin Maniac');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (30, 'Beverly', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (31, 'Andres', 'Ruin Maniac');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (32, 'Josue', 'Bird Keeper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (33, 'Luis', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (34, 'Ned', 'Fisherman');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (35, 'Elliot', 'Fisherman');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (36, 'Douglas', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (37, 'Kyla', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (38, 'Denise', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (39, 'Tony', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (40, 'Lisa & Ray', 'Sis and Bro');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (41, 'Darrin', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (42, 'Beth', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (43, 'Camron', 'Triathlete');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (44, 'Missy', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (45, 'Matthew', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (46, 'Tara', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (47, 'Carolina', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (48, 'Cory', 'Sailor');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (49, 'Jerome', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (50, 'Huey', 'Sailor');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (51, 'Edmond', 'Sailor');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (52, 'Hailey', 'Tuber');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (53, 'Ricky', 'Tuber');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (54, 'Lola', 'Tuber');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (55, 'Chandler', 'Tuber');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (56, 'Simon', 'Tuber');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (57, 'Johanna', 'Beauty');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (58, 'Dwayne', 'Sailor');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (59, 'Austina', 'Tuber');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (60, 'Gwen', 'Tuber');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (61, 'David', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (62, 'Alice', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (63, 'Carter', 'Fisherman');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (64, 'Elijah', 'Bird Keeper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (65, 'Mel & Paul', 'Young Couple');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (66, 'Isabel', 'Pokefan');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (67, 'Kaleb', 'Pokefan');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (68, 'Timmy', 'Youngster');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (69, 'Edwin', 'Collector');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (70, 'Joseph', 'Guitarist');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (71, 'Edward', 'Psychic');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (72, 'Alyssa', 'Triathlete');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (73, 'Dale', 'Fisherman');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (74, 'Victor', 'Winstrate');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (75, 'Victoria', 'Winstrate');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (76, 'Vivi', 'Winstrate');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (77, 'Vicky', 'Winstrate');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (78, 'Tyron', 'Camper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (79, 'Celina', 'Aroma Lady');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (80, 'Bianca', 'Picnicker');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (81, 'Hayden', 'Kindler');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (82, 'Gabby and Ty', 'Interviewer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (83, 'Irene', 'Picnicker');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (84, 'Travis', 'Camper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (85, 'Heidi', 'Picnicker');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (86, 'Beau', 'Camper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (87, 'Drew', 'Camper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (88, 'Becky', 'Picnicker');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (89, 'Dusty', 'Ruin Maniac');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (90, 'Celia', 'Picnicker');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (91, 'Bryan', 'Ruin Maniac');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (92, 'Branden', 'Camper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (93, 'Wilton', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (94, 'Brooke', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (95, 'Daisuke', 'Black Belt');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (96, 'Larry', 'Camper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (97, 'Carol', 'Picnicker');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (98, 'Trent', 'Hiker');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (99, 'Brice', 'Hiker');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (100, 'Bryant', 'Kindler');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (101, 'Shayla', 'Aroma Lady');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (102, 'Jaylen', 'Youngster');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (103, 'Lawrence', 'Camper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (104, 'Lung', 'Ninja Boy');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (105, 'Wyatt', 'PokeManiac');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (106, 'Madeline', 'Parasol Lady');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (107, 'Tori & Tia', 'Twins');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (108, 'Lao', 'Ninja Boy');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (109, 'Dillon', 'Youngster');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (110, 'Sophie', 'Picnicker');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (111, 'Coby', 'Bird Keeper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (112, 'Nolan', 'Fisherman');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (113, 'Charlotte', 'Picnicker');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (114, 'Kai', 'Fisherman');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (115, 'Claude', 'Fisherman');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (116, 'Nancy', 'Picnicker');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (117, 'Tyra & Ivy', 'Sr. and Jr.');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (118, 'Shane', 'Camper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (119, 'Steve', 'PokeManiac');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (120, 'Bernie', 'Kindler');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (121, 'Lucas', 'Hiker');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (122, 'Angelina', 'Picnicker');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (123, 'Lenny', 'Hiker');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (124, 'Nob', 'Black Belt');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (125, 'Hector', 'Collector');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (126, 'Marlene', 'Psychic');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (127, 'Cyndy', 'Battle Girl');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (128, 'Jaiden', 'Ninja Boy');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (129, 'Timothy', 'Expert');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (130, 'Kyra', 'Triathlete');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (131, 'Koichi', 'Black Belt');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (132, 'Helene', 'Battle Girl');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (133, 'Alix', 'Psychic');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (134, 'Jose', 'Bug Catcher');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (135, 'Joey', 'Youngster');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (136, 'Karen', 'School Kid');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (137, 'Clark', 'Hiker');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (138, 'Johnson', 'Youngster');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (139, 'Devan', 'Hiker');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (140, 'Sarah', 'Lady');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (141, 'Dawson', 'Rich Boy');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (142, 'Jerry', 'School Kid');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (143, 'Janice', 'Lass');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (144, 'Dylan', 'Triathlete');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (145, 'Anna & Meg', 'Sr. and Jr.');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (146, 'Isaac', 'Pokemon Breeder');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (147, 'Maria', 'Triathlete');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (148, 'Derek', 'Bug Maniac');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (149, 'Brandi', 'Psychic');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (150, 'Melina', 'Triathlete');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (151, 'Aisha', 'Battle Girl');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (152, 'Lydia', 'Pokemon Breeder');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (153, 'Rose', 'Aroma Lady');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (154, 'Deandre', 'Youngster');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (155, 'Wade', 'Fisherman');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (156, 'Dalton', 'Guitarist');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (157, 'Barny', 'Fisherman');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (158, 'Chester', 'Bird Keeper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (159, 'Perry', 'Bird Keeper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (160, 'Kent', 'Bug Catcher');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (161, 'Donald', 'Bug Maniac');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (162, 'Greg', 'Bug Catcher');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (163, 'Taylor', 'Bug Maniac');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (164, 'Doug', 'Bug Catcher');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (165, 'Brent', 'Bug Maniac');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (166, 'Chris', 'Fisherman');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (167, 'Catherine', 'Pokemon Ranger');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (168, 'Jackson', 'Pokemon Ranger');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (169, 'Rachel', 'Parasol Lady');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (170, 'Phil', 'Bird Keeper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (171, 'Takashi', 'Ninja Boy');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (172, 'Dayton', 'Kindler');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (173, 'Hugh', 'Bird Keeper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (174, 'Fabian', 'Guitarist');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (175, 'Yasu', 'Ninja Boy');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (176, 'Hideo', 'Ninja Boy');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (177, 'Clarissa', 'Parasol Lady');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (178, 'Robert', 'Bird Keeper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (179, 'Colin', 'Bird Keeper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (180, 'Leonel', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (181, 'Angelica', 'Parasol Lady');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (182, 'Riley', 'Ninja Boy');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (183, 'Callie', 'Battle Girl');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (184, 'Jennifer', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (185, 'Jenna', 'Pokemon Ranger');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (186, 'Lorenzo', 'Pokemon Ranger');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (187, 'Jeffrey', 'Bug Maniac');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (188, 'Keigo', 'Ninja Boy');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (189, 'Chip', 'Ruin Maniac');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (190, 'Cale', 'Bug Maniac');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (191, 'Tammy', 'Hex Maniac');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (192, 'Jessica', 'Beauty');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (193, 'Kate & Joy', 'Sr. and Jr.');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (194, 'Pat', 'Pokemon Breeder');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (195, 'Myles', 'Pokemon Breeder');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (196, 'Walter', 'Gentleman');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (197, 'Vanessa', 'Pokefan');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (198, 'Marcel', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (199, 'Cristin', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (200, 'Davis', 'Bug Catcher');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (201, 'Jazmyn', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (202, 'Violet', 'Aroma Lady');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (203, 'Miu & Yuki', 'Twins');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (204, 'Kindra', 'Hex Maniac');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (205, 'Ed', 'Collector');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (206, 'Wendy', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (207, 'Braxton', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (208, 'Fernando', 'Guitarist');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (209, 'Alberto', 'Bird Keeper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (210, 'Jacki', 'Psychic');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (211, 'Fredrick', 'Expert');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (212, 'Cameron', 'Psychic');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (213, 'Jonas', 'Ninja Boy');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (214, 'Kayley', 'Parasol Lady');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (215, 'Grace', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (216, 'Declan', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (217, 'Lila & Roy', 'Sis and Bro');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (218, 'Spencer', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (219, 'Jenny', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (220, 'Chad', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (221, 'Isabella', 'Triathlete');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (222, 'Roland', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (223, 'Ernest', 'Sailor');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (224, 'Nolen', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (225, 'Sharon', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (226, 'Tanya', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (227, 'Presley', 'Bird Keeper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (228, 'Auron', 'Expert');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (229, 'Stan', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (230, 'Kim & Iris', 'Sr. and Jr.');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (231, 'Leonardo', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (232, 'Isobel', 'Triathlete');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (233, 'Dean', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (234, 'Nikki', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (235, 'Barry', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (236, 'Sienna', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (237, 'Pablo', 'Triathlete');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (238, 'Brenda', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (239, 'Aidan', 'Bird Keeper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (240, 'Athena', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (241, 'Jonah', 'Fisherman');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (242, 'Roger', 'Fisherman');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (243, 'Henry', 'Fisherman');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (244, 'Camden', 'Triathlete');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (245, 'Koji', 'Black Belt');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (246, 'Donny', 'Triathlete');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (247, 'Ruben', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (248, 'Alexa', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (249, 'Wayne', 'Fisherman');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (250, 'Isaiah', 'Triathlete');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (251, 'Katelyn', 'Triathlete');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (252, 'Carlee', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (253, 'Harrison', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (254, 'Reed', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (255, 'Chase', 'Triathlete');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (256, 'Allison', 'Triathlete');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (257, 'Clarence', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (258, 'Tisha', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (259, 'Rodney', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (260, 'Katie', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (261, 'Santiago', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (262, 'Kevin', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (263, 'Taila', 'Triathlete');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (264, 'Richard', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (265, 'Kara', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (266, 'Herman', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (267, 'Susie', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (268, 'Reli & Ian', 'Sis and Bro');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (269, 'Gilbert', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (270, 'Dana', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (271, 'Ronald', 'Fisherman');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (272, 'Kiyo', 'Black Belt');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (273, 'Paxton', 'Expert');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (274, 'Darcy', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (275, 'Makayla', 'Expert');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (276, 'Jonathan', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (277, 'Linda', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (278, 'Beck', 'Bird Keeper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (279, 'Conor', 'Expert');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (280, 'Mollie', 'Expert');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (281, 'Warren', 'Cool Trainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (282, 'Debra', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (283, 'Franklin', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (284, 'Laurel', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (285, 'Jack', 'Swimmer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (286, 'Hitoshi', 'Black Belt');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (287, 'Reyna', 'Battle Girl');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (288, 'Hudson', 'Sailor');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (289, 'Aaron', 'Dragon Tamer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (290, 'Marley', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (291, 'Alex', 'Bird Keeper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (292, 'Kelvin', 'Sailor');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (293, 'Eric', 'Hiker');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (294, 'NULL', 'Team Magma Grunt');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (295, 'Diana', 'Picnicker');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (296, 'Autumn', 'Picnicker');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (297, 'Julio', 'Triathlete');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (298, 'Ethan', 'Camper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (299, 'Tabitha', 'Magma Admin');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (300, 'Maxie', 'Magma Leader');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (301, 'Wally', 'Pokemon Trainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (302, 'John and Jay', 'Old Couple');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (303, 'Nicolas', 'Dragon Tamer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (304, 'Steven', 'Pokemon Trainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (305, 'Shirley', 'Beauty');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (306, 'Sheila', 'Beauty');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (307, 'Shelby', 'Expert');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (308, 'Sawyer', 'Hiker');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (309, 'Melissa', 'Beauty');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (310, 'Mark', 'PokeManiac');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (311, 'Leah', 'Hex Maniac');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (312, 'Zander', 'Black Belt');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (313, 'Dez & Luke', 'Young Couple');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (314, 'Kayla', 'Psychic');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (315, 'Gabrielle', 'Pokemon Breeder');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (316, 'William', 'Psychic');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (317, 'Tasha', 'Hex Maniac');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (318, 'Atsushi', 'Black Belt');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (319, 'Valerie', 'Hex Maniac');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (320, 'Cedric', 'Psychic');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (321, 'NULL', 'Team Aqua Grunt');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (322, 'Lyle', 'Bug Catcher');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (323, 'James', 'Bug Catcher');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (326, 'Mike', 'Hiker');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (327, 'Lea & Jed', 'Young Couple');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (328, 'Garret', 'Rich Boy');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (329, 'Tucker', 'Gentleman');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (330, 'Colton', 'Pokefan');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (331, 'Anette', 'Lady');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (332, 'Thomas', 'Gentleman');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (333, 'Phillip', 'Sailor');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (334, 'Leonard', 'Sailor');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (335, 'Shelly', 'Aqua Admin');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (336, 'Archie', 'Aqua Leader');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (337, 'Jaclyn', 'Psychic');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (338, 'Abigail', 'Triathlete');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (339, 'Anthony', 'Triathlete');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (340, 'Benjamin', 'Triathlete');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (341, 'Jasmine', 'Triathlete');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (342, 'Jacob', 'Triathlete');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (343, 'Matt', 'Aqua Admin');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (344, 'Shigenobu', 'Youngster');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (345, 'Akari', 'Parasol Lady');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (346, 'Shigezo', 'Ninja Boy');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (347, 'Namiko', 'Beauty');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (348, 'Makie', 'Hex Maniac');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (349, 'Haruhito', 'Camper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (350, 'Meiko', 'School Kid');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (351, 'Pierre', 'Gentleman');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (352, 'Alfonso', 'Triathlete');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (353, 'Alaina', 'Hex Maniac');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (354, 'Theodore', 'Black Belt');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (355, 'Jayden', 'Pokemon Breeder');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (356, 'Salvadore', 'Pokemon Breeder');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (357, 'Veronica', 'Pokemon Breeder');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (358, 'Keenan', 'Psychic');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (359, 'Kristina', 'Aroma Lady');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (360, 'Terrance', 'Gentleman');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (361, 'Elizabeth', 'Lady');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (362, 'Annabell', 'Parasol Lady');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (363, 'Coleman', 'Collector');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (364, 'Enrique', 'Rich Boy');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (365, 'Colleen', 'Lady');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (366, 'Kimberly', 'Pokefan');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (367, 'Francisco', 'Pokefan');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (368, 'Bernard', 'Kindler');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (369, 'Merdith', 'Pokemon Ranger');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (370, 'Abraham', 'Ruin Maniac');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (371, 'Luc', 'Tuber');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (372, 'Breyden', 'Youngster');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (373, 'Aniya', 'Tuber');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (374, 'Dane', 'Bird Keeper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (375, 'Stephanie', 'Triathlete');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (376, 'Alfred', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (377, 'Edie', 'Psychic');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (378, 'Roderick', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (379, 'Alicia', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (380, 'Terrence', 'Expert');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (381, 'Carlotta', 'Expert');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (382, 'Nora', 'Pokemon Ranger');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (383, 'Gav', 'Pokemon Ranger');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (384, 'Sally', 'Lass');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (385, 'Robin', 'Lass');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (386, 'Eddie', 'Youngster');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (387, 'Ted', 'School Kid');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (388, 'Paul', 'School Kid');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (389, 'Georgia', 'School Kid');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (390, 'Justin', 'Camper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (391, 'Martha', 'Picnicker');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (392, 'Alan', 'Hiker');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (393, 'Yuji', 'Black Belt');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (394, 'Cora', 'Battle Girl');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (395, 'Jill', 'Battle Girl');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (396, 'Sophia', 'Pokemon Ranger');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (397, 'Sebastian', 'Pokemon Ranger');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (398, 'Benny', 'Bird Keeper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (399, 'Joshua', 'Psychic');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (400, 'Patricia', 'Hex Maniac');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (401, 'Mariella', 'Psychic');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (402, 'Everett', 'Gentleman');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (403, 'Alexis', 'Psychic');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (404, 'Alvaro', 'Psychic');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (405, 'Elaine', 'Cool Trainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (406, 'Vincent', 'Cool Trainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (407, 'Leroy', 'Cool Trainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (408, 'Albert', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (409, 'Hope', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (410, 'Shannon', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (411, 'Samuel', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (412, 'Julie', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (413, 'Owen', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (414, 'Dianne', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (415, 'Felix', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (416, 'Caroline', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (417, 'Vito', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (418, 'Michelle', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (419, 'Mitchell', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (420, 'Halle', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (421, 'Edgar', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (422, 'Katelynn', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (423, 'Quincy', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (424, 'Josh', 'Youngster');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (425, 'Tommy', 'Youngster');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (426, 'Marc', 'Hiker');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (427, 'Roxanne', 'Leader');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (428, 'Laura', 'Battle Girl');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (429, 'Lilith', 'Battle Girl');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (430, 'Brenden', 'Sailor');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (431, 'Takao', 'Black Belt');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (432, 'Christian', 'Black Belt');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (433, 'Jocelyn', 'Battle Girl');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (434, 'Brawly', 'Leader');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (435, 'Vivian', 'Battle Girl');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (436, 'Kirk', 'Guitarist');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (437, 'Ben', 'Youngster');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (438, 'Angelo', 'Bug Maniac');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (439, 'Shawn', 'Guitarist');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (440, 'Wattson', 'Leader');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (441, 'Jeff', 'Kindler');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (442, 'Jace', 'Kindler');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (443, 'Eli', 'Hiker');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (444, 'Cole', 'Kindler');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (445, 'Gerald', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (446, 'Axle', 'Kindler');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (447, 'Keegan', 'Kindler');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (448, 'Danielle', 'Battle Girl');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (449, 'Flannery', 'Leader');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (450, 'Randall', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (451, 'Mary', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (452, 'Parker', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (453, 'Alexia', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (454, 'George', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (455, 'Jody', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (456, 'Berke', 'Cooltrainer');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (457, 'Norman', 'Leader');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (458, 'Humberto', 'Bird Keeper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (459, 'Jared', 'Bird Keeper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (460, 'Ashley', 'Picnicker');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (461, 'Flint', 'Camper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (462, 'Edwardo', 'Bird Keeper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (463, 'Darius', 'Bird Keeper');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (464, 'Winona', 'Leader');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (465, 'Preston', 'Psychic');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (466, 'Maura', 'Psychic');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (467, 'Samantha', 'Psychic');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (468, 'Blake', 'Psychic');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (469, 'Macey', 'Psychic');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (470, 'Clifford', 'Gentleman');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (471, 'Kathleen', 'Hex Maniac');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (472, 'Nicholas', 'Psychic');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (473, 'Nate', 'Gentleman');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (474, 'Virgil', 'Psychic');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (475, 'Sylvia', 'Hex Maniac');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (476, 'Hannah', 'Psychic');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (477, 'Tate & Liza', 'Leader');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (478, 'Connie', 'Beauty');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (479, 'Andrea', 'Lass');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (480, 'Daphne', 'Lady');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (481, 'Annika', 'Pokefan');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (482, 'Tiffany', 'Beauty');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (483, 'Crissy', 'Lass');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (484, 'Bethany', 'Pokefan');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (485, 'Olivia', 'Beauty');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (486, 'Brianna', 'Lady');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (487, 'Bridget', 'Beauty');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (488, 'Juan', 'Leader');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (489, 'Billy', 'Youngster');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (490, 'Darian', 'Fisherman');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (491, 'Cindy', 'Lady');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (492, 'Winston', 'Rich Boy');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (493, 'Haley', 'Lass');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (494, 'Gina & Mia', 'Twins');
INSERT INTO Trainer (TID, TrainerName, TrainerClass) VALUES (495, 'Ivan', 'Fisherman');
