INSERT INTO GROUP07."Abilities" VALUES (1,'Overgrow');
INSERT INTO GROUP07."Abilities" VALUES (2,'Overgrow');
INSERT INTO GROUP07."Abilities" VALUES (3,'Overgrow');
INSERT INTO GROUP07."Abilities" VALUES (4,'Blaze');
INSERT INTO GROUP07."Abilities" VALUES (5,'Blaze');
INSERT INTO GROUP07."Abilities" VALUES (6,'Blaze');
INSERT INTO GROUP07."Abilities" VALUES (7,'Torrent');
INSERT INTO GROUP07."Abilities" VALUES (8,'Torrent');
INSERT INTO GROUP07."Abilities" VALUES (9,'Torrent');
INSERT INTO GROUP07."Abilities" VALUES (10,'Shield Dust');
INSERT INTO GROUP07."Abilities" VALUES (11,'Shed Skin');
INSERT INTO GROUP07."Abilities" VALUES (12,'Compound Eyes');
INSERT INTO GROUP07."Abilities" VALUES (13,'Shield Dust');
INSERT INTO GROUP07."Abilities" VALUES (14,'Shed Skin');
INSERT INTO GROUP07."Abilities" VALUES (15,'Swarm');
INSERT INTO GROUP07."Abilities" VALUES (16,'Keen Eye');
INSERT INTO GROUP07."Abilities" VALUES (16,'Tangled Feet');
INSERT INTO GROUP07."Abilities" VALUES (17,'Keen Eye');
INSERT INTO GROUP07."Abilities" VALUES (17,'Tangled Feet');
INSERT INTO GROUP07."Abilities" VALUES (18,'Keen Eye');
INSERT INTO GROUP07."Abilities" VALUES (18,'Tangled Feet');
INSERT INTO GROUP07."Abilities" VALUES (19,'Run Away');
INSERT INTO GROUP07."Abilities" VALUES (19,'Guts');
INSERT INTO GROUP07."Abilities" VALUES (20,'Run Away');
INSERT INTO GROUP07."Abilities" VALUES (20,'Guts');
INSERT INTO GROUP07."Abilities" VALUES (21,'Keen Eye');
INSERT INTO GROUP07."Abilities" VALUES (22,'Keen Eye');
INSERT INTO GROUP07."Abilities" VALUES (23,'Intimidate');
INSERT INTO GROUP07."Abilities" VALUES (23,'Shed Skin');
INSERT INTO GROUP07."Abilities" VALUES (24,'Intimidate');
INSERT INTO GROUP07."Abilities" VALUES (24,'Shed Skin');
INSERT INTO GROUP07."Abilities" VALUES (25,'Static');
INSERT INTO GROUP07."Abilities" VALUES (26,'Static');
INSERT INTO GROUP07."Abilities" VALUES (27,'Sand Veil');
INSERT INTO GROUP07."Abilities" VALUES (28,'Sand Veil');
INSERT INTO GROUP07."Abilities" VALUES (29,'Poison Point');
INSERT INTO GROUP07."Abilities" VALUES (29,'Rivalry');
INSERT INTO GROUP07."Abilities" VALUES (30,'Poison Point');
INSERT INTO GROUP07."Abilities" VALUES (30,'Rivalry');
INSERT INTO GROUP07."Abilities" VALUES (31,'Poison Point');
INSERT INTO GROUP07."Abilities" VALUES (31,'Rivalry');
INSERT INTO GROUP07."Abilities" VALUES (32,'Poison Point');
INSERT INTO GROUP07."Abilities" VALUES (32,'Rivalry');
INSERT INTO GROUP07."Abilities" VALUES (33,'Poison Point');
INSERT INTO GROUP07."Abilities" VALUES (33,'Rivalry');
INSERT INTO GROUP07."Abilities" VALUES (34,'Poison Point');
INSERT INTO GROUP07."Abilities" VALUES (34,'Rivalry');
INSERT INTO GROUP07."Abilities" VALUES (35,'Cute Charm');
INSERT INTO GROUP07."Abilities" VALUES (35,'Magic Guard');
INSERT INTO GROUP07."Abilities" VALUES (36,'Cute Charm');
INSERT INTO GROUP07."Abilities" VALUES (36,'Magic Guard');
INSERT INTO GROUP07."Abilities" VALUES (37,'Flash Fire');
INSERT INTO GROUP07."Abilities" VALUES (38,'Flash Fire');
INSERT INTO GROUP07."Abilities" VALUES (39,'Cute Charm');
INSERT INTO GROUP07."Abilities" VALUES (39,'Competitive');
INSERT INTO GROUP07."Abilities" VALUES (40,'Cute Charm');
INSERT INTO GROUP07."Abilities" VALUES (40,'Competitive');
INSERT INTO GROUP07."Abilities" VALUES (41,'Inner Focus');
INSERT INTO GROUP07."Abilities" VALUES (42,'Inner Focus');
INSERT INTO GROUP07."Abilities" VALUES (43,'Chlorophyll');
INSERT INTO GROUP07."Abilities" VALUES (44,'Chlorophyll');
INSERT INTO GROUP07."Abilities" VALUES (45,'Chlorophyll');
INSERT INTO GROUP07."Abilities" VALUES (46,'Effect Spore');
INSERT INTO GROUP07."Abilities" VALUES (46,'Dry Skin');
INSERT INTO GROUP07."Abilities" VALUES (47,'Effect Spore');
INSERT INTO GROUP07."Abilities" VALUES (47,'Dry Skin');
INSERT INTO GROUP07."Abilities" VALUES (48,'Compound Eyes');
INSERT INTO GROUP07."Abilities" VALUES (48,'Tinted Lens');
INSERT INTO GROUP07."Abilities" VALUES (49,'Shield Dust');
INSERT INTO GROUP07."Abilities" VALUES (49,'Tinted Lens');
INSERT INTO GROUP07."Abilities" VALUES (50,'Sand Veil');
INSERT INTO GROUP07."Abilities" VALUES (50,'Arena Trap');
INSERT INTO GROUP07."Abilities" VALUES (51,'Sand Veil');
INSERT INTO GROUP07."Abilities" VALUES (51,'Arena Trap');
INSERT INTO GROUP07."Abilities" VALUES (52,'Pickup');
INSERT INTO GROUP07."Abilities" VALUES (52,'Technician');
INSERT INTO GROUP07."Abilities" VALUES (53,'Limber');
INSERT INTO GROUP07."Abilities" VALUES (53,'Technician');
INSERT INTO GROUP07."Abilities" VALUES (54,'Damp');
INSERT INTO GROUP07."Abilities" VALUES (54,'Cloud Nine');
INSERT INTO GROUP07."Abilities" VALUES (55,'Damp');
INSERT INTO GROUP07."Abilities" VALUES (55,'Cloud Nine');
INSERT INTO GROUP07."Abilities" VALUES (56,'Vital Spirit');
INSERT INTO GROUP07."Abilities" VALUES (56,'Anger Point');
INSERT INTO GROUP07."Abilities" VALUES (57,'Vital Spirit');
INSERT INTO GROUP07."Abilities" VALUES (57,'Anger Point');
INSERT INTO GROUP07."Abilities" VALUES (58,'Intimidate');
INSERT INTO GROUP07."Abilities" VALUES (58,'Flash Fire');
INSERT INTO GROUP07."Abilities" VALUES (59,'Intimidate');
INSERT INTO GROUP07."Abilities" VALUES (59,'Flash Fire');
INSERT INTO GROUP07."Abilities" VALUES (60,'Water Absorb');
INSERT INTO GROUP07."Abilities" VALUES (60,'Damp');
INSERT INTO GROUP07."Abilities" VALUES (61,'Water Absorb');
INSERT INTO GROUP07."Abilities" VALUES (61,'Damp');
INSERT INTO GROUP07."Abilities" VALUES (62,'Water Absorb');
INSERT INTO GROUP07."Abilities" VALUES (62,'Damp');
INSERT INTO GROUP07."Abilities" VALUES (63,'Synchronize');
INSERT INTO GROUP07."Abilities" VALUES (63,'Inner Focus');
INSERT INTO GROUP07."Abilities" VALUES (64,'Synchronize');
INSERT INTO GROUP07."Abilities" VALUES (64,'Inner Focus');
INSERT INTO GROUP07."Abilities" VALUES (65,'Synchronize');
INSERT INTO GROUP07."Abilities" VALUES (65,'Inner Focus');
INSERT INTO GROUP07."Abilities" VALUES (66,'Guts');
INSERT INTO GROUP07."Abilities" VALUES (66,'No Guard');
INSERT INTO GROUP07."Abilities" VALUES (67,'Guts');
INSERT INTO GROUP07."Abilities" VALUES (67,'No Guard');
INSERT INTO GROUP07."Abilities" VALUES (68,'Guts');
INSERT INTO GROUP07."Abilities" VALUES (68,'No Guard');
INSERT INTO GROUP07."Abilities" VALUES (69,'Chlorophyll');
INSERT INTO GROUP07."Abilities" VALUES (70,'Chlorophyll');
INSERT INTO GROUP07."Abilities" VALUES (71,'Chlorophyll');
INSERT INTO GROUP07."Abilities" VALUES (72,'Clear Body');
INSERT INTO GROUP07."Abilities" VALUES (72,'Liquid Ooze');
INSERT INTO GROUP07."Abilities" VALUES (73,'Clear Body');
INSERT INTO GROUP07."Abilities" VALUES (73,'Liquid Ooze');
INSERT INTO GROUP07."Abilities" VALUES (74,'Rock Head');
INSERT INTO GROUP07."Abilities" VALUES (74,'Sturdy');
INSERT INTO GROUP07."Abilities" VALUES (75,'Rock Head');
INSERT INTO GROUP07."Abilities" VALUES (75,'Sturdy');
INSERT INTO GROUP07."Abilities" VALUES (76,'Rock Head');
INSERT INTO GROUP07."Abilities" VALUES (76,'Sturdy');
INSERT INTO GROUP07."Abilities" VALUES (77,'Run Away');
INSERT INTO GROUP07."Abilities" VALUES (77,'Flash Fire');
INSERT INTO GROUP07."Abilities" VALUES (78,'Run Away');
INSERT INTO GROUP07."Abilities" VALUES (78,'Flash Fire');
INSERT INTO GROUP07."Abilities" VALUES (79,'Oblivious');
INSERT INTO GROUP07."Abilities" VALUES (79,'Own Tempo');
INSERT INTO GROUP07."Abilities" VALUES (80,'Oblivious');
INSERT INTO GROUP07."Abilities" VALUES (80,'Own Tempo');
INSERT INTO GROUP07."Abilities" VALUES (81,'Magnet Pull');
INSERT INTO GROUP07."Abilities" VALUES (81,'Sturdy');
INSERT INTO GROUP07."Abilities" VALUES (82,'Magnet Pull');
INSERT INTO GROUP07."Abilities" VALUES (82,'Sturdy');
INSERT INTO GROUP07."Abilities" VALUES (83,'Keen Eye');
INSERT INTO GROUP07."Abilities" VALUES (83,'Inner Focus');
INSERT INTO GROUP07."Abilities" VALUES (84,'Run Away');
INSERT INTO GROUP07."Abilities" VALUES (84,'Early Bird');
INSERT INTO GROUP07."Abilities" VALUES (85,'Run Away');
INSERT INTO GROUP07."Abilities" VALUES (85,'Early Bird');
INSERT INTO GROUP07."Abilities" VALUES (86,'Thick Fat');
INSERT INTO GROUP07."Abilities" VALUES (86,'Hydration');
INSERT INTO GROUP07."Abilities" VALUES (87,'Thick Fat');
INSERT INTO GROUP07."Abilities" VALUES (87,'Hydration');
INSERT INTO GROUP07."Abilities" VALUES (88,'Stench');
INSERT INTO GROUP07."Abilities" VALUES (88,'Sticky Hold');
INSERT INTO GROUP07."Abilities" VALUES (89,'Stench');
INSERT INTO GROUP07."Abilities" VALUES (89,'Sticky Hold');
INSERT INTO GROUP07."Abilities" VALUES (90,'Shell Armor');
INSERT INTO GROUP07."Abilities" VALUES (90,'Skill Link');
INSERT INTO GROUP07."Abilities" VALUES (91,'Shell Armor');
INSERT INTO GROUP07."Abilities" VALUES (91,'Skill Link');
INSERT INTO GROUP07."Abilities" VALUES (92,'Levitate');
INSERT INTO GROUP07."Abilities" VALUES (93,'Levitate');
INSERT INTO GROUP07."Abilities" VALUES (94,'Cursed Body');
INSERT INTO GROUP07."Abilities" VALUES (95,'Rock Head');
INSERT INTO GROUP07."Abilities" VALUES (95,'Sturdy');
INSERT INTO GROUP07."Abilities" VALUES (96,'Insomnia');
INSERT INTO GROUP07."Abilities" VALUES (96,'Forewarn');
INSERT INTO GROUP07."Abilities" VALUES (97,'Insomnia');
INSERT INTO GROUP07."Abilities" VALUES (97,'Forewarn');
INSERT INTO GROUP07."Abilities" VALUES (98,'Hyper Cutter');
INSERT INTO GROUP07."Abilities" VALUES (98,'Shell Armor');
INSERT INTO GROUP07."Abilities" VALUES (99,'Hyper Cutter');
INSERT INTO GROUP07."Abilities" VALUES (99,'Shell Armor');
INSERT INTO GROUP07."Abilities" VALUES (100,'Soundproof');
INSERT INTO GROUP07."Abilities" VALUES (100,'Static');
INSERT INTO GROUP07."Abilities" VALUES (101,'Soundproof');
INSERT INTO GROUP07."Abilities" VALUES (101,'Static');
INSERT INTO GROUP07."Abilities" VALUES (102,'Chlorophyll');
INSERT INTO GROUP07."Abilities" VALUES (103,'Chlorophyll');
INSERT INTO GROUP07."Abilities" VALUES (104,'Rock Head');
INSERT INTO GROUP07."Abilities" VALUES (104,'Lightning Rod');
INSERT INTO GROUP07."Abilities" VALUES (105,'Rock Head');
INSERT INTO GROUP07."Abilities" VALUES (105,'Lightning Rod');
INSERT INTO GROUP07."Abilities" VALUES (106,'Limber');
INSERT INTO GROUP07."Abilities" VALUES (106,'Reckless');
INSERT INTO GROUP07."Abilities" VALUES (107,'Keen Eye');
INSERT INTO GROUP07."Abilities" VALUES (107,'Iron Fist');
INSERT INTO GROUP07."Abilities" VALUES (108,'Own Tempo');
INSERT INTO GROUP07."Abilities" VALUES (108,'Oblivious');
INSERT INTO GROUP07."Abilities" VALUES (109,'Levitate');
INSERT INTO GROUP07."Abilities" VALUES (109,'Neutralizing Gas');
INSERT INTO GROUP07."Abilities" VALUES (110,'Levitate');
INSERT INTO GROUP07."Abilities" VALUES (110,'Neutralizing Gas');
INSERT INTO GROUP07."Abilities" VALUES (111,'Lightning Rod');
INSERT INTO GROUP07."Abilities" VALUES (111,'Rock Head');
INSERT INTO GROUP07."Abilities" VALUES (112,'Lightning Rod');
INSERT INTO GROUP07."Abilities" VALUES (112,'Rock Head');
INSERT INTO GROUP07."Abilities" VALUES (113,'Natural Cure');
INSERT INTO GROUP07."Abilities" VALUES (113,'Serene Grace');
INSERT INTO GROUP07."Abilities" VALUES (114,'Chlorophyll');
INSERT INTO GROUP07."Abilities" VALUES (114,'Leaf Guard');
INSERT INTO GROUP07."Abilities" VALUES (115,'Early Bird');
INSERT INTO GROUP07."Abilities" VALUES (115,'Scrappy');
INSERT INTO GROUP07."Abilities" VALUES (116,'Swift Swim');
INSERT INTO GROUP07."Abilities" VALUES (116,'Sniper');
INSERT INTO GROUP07."Abilities" VALUES (117,'Poison Point');
INSERT INTO GROUP07."Abilities" VALUES (117,'Sniper');
INSERT INTO GROUP07."Abilities" VALUES (118,'Swift Swim');
INSERT INTO GROUP07."Abilities" VALUES (118,'Water Veil');
INSERT INTO GROUP07."Abilities" VALUES (119,'Swift Swim');
INSERT INTO GROUP07."Abilities" VALUES (119,'Water Veil');
INSERT INTO GROUP07."Abilities" VALUES (120,'Illuminate');
INSERT INTO GROUP07."Abilities" VALUES (120,'Natural Cure');
INSERT INTO GROUP07."Abilities" VALUES (121,'Illuminate');
INSERT INTO GROUP07."Abilities" VALUES (121,'Natural Cure');
INSERT INTO GROUP07."Abilities" VALUES (122,'Soundproof');
INSERT INTO GROUP07."Abilities" VALUES (122,'Filter');
INSERT INTO GROUP07."Abilities" VALUES (123,'Swarm');
INSERT INTO GROUP07."Abilities" VALUES (123,'Technician');
INSERT INTO GROUP07."Abilities" VALUES (124,'Oblivious');
INSERT INTO GROUP07."Abilities" VALUES (124,'Forewarn');
INSERT INTO GROUP07."Abilities" VALUES (125,'Static');
INSERT INTO GROUP07."Abilities" VALUES (126,'Flame Body');
INSERT INTO GROUP07."Abilities" VALUES (127,'Hyper Cutter');
INSERT INTO GROUP07."Abilities" VALUES (127,'Mold Breaker');
INSERT INTO GROUP07."Abilities" VALUES (128,'Intimidate');
INSERT INTO GROUP07."Abilities" VALUES (128,'Anger Point');
INSERT INTO GROUP07."Abilities" VALUES (129,'Swift Swim');
INSERT INTO GROUP07."Abilities" VALUES (130,'Intimidate');
INSERT INTO GROUP07."Abilities" VALUES (131,'Water Absorb');
INSERT INTO GROUP07."Abilities" VALUES (131,'Shell Armor');
INSERT INTO GROUP07."Abilities" VALUES (132,'Limber');
INSERT INTO GROUP07."Abilities" VALUES (133,'Run Away');
INSERT INTO GROUP07."Abilities" VALUES (133,'Adaptability');
INSERT INTO GROUP07."Abilities" VALUES (134,'Water Absorb');
INSERT INTO GROUP07."Abilities" VALUES (135,'Volt Absorb');
INSERT INTO GROUP07."Abilities" VALUES (136,'Flash Fire');
INSERT INTO GROUP07."Abilities" VALUES (137,'Trace');
INSERT INTO GROUP07."Abilities" VALUES (137,'Download');
INSERT INTO GROUP07."Abilities" VALUES (138,'Swift Swim');
INSERT INTO GROUP07."Abilities" VALUES (138,'Shell Armor');
INSERT INTO GROUP07."Abilities" VALUES (139,'Swift Swim');
INSERT INTO GROUP07."Abilities" VALUES (139,'Shell Armor');
INSERT INTO GROUP07."Abilities" VALUES (140,'Swift Swim');
INSERT INTO GROUP07."Abilities" VALUES (140,'Battle Armor');
INSERT INTO GROUP07."Abilities" VALUES (141,'Swift Swim');
INSERT INTO GROUP07."Abilities" VALUES (141,'Battle Armor');
INSERT INTO GROUP07."Abilities" VALUES (142,'Rock Head');
INSERT INTO GROUP07."Abilities" VALUES (142,'Pressure');
INSERT INTO GROUP07."Abilities" VALUES (143,'Immunity');
INSERT INTO GROUP07."Abilities" VALUES (143,'Thick Fat');
INSERT INTO GROUP07."Abilities" VALUES (144,'Pressure');
INSERT INTO GROUP07."Abilities" VALUES (145,'Pressure');
INSERT INTO GROUP07."Abilities" VALUES (146,'Pressure');
INSERT INTO GROUP07."Abilities" VALUES (147,'Shed Skin');
INSERT INTO GROUP07."Abilities" VALUES (148,'Shed Skin');
INSERT INTO GROUP07."Abilities" VALUES (149,'Inner Focus');
INSERT INTO GROUP07."Abilities" VALUES (150,'Pressure');
INSERT INTO GROUP07."Abilities" VALUES (151,'Synchronize');
INSERT INTO GROUP07."Abilities" VALUES (152,'Overgrow');
INSERT INTO GROUP07."Abilities" VALUES (153,'Overgrow');
INSERT INTO GROUP07."Abilities" VALUES (154,'Overgrow');
INSERT INTO GROUP07."Abilities" VALUES (155,'Blaze');
INSERT INTO GROUP07."Abilities" VALUES (156,'Blaze');
INSERT INTO GROUP07."Abilities" VALUES (157,'Blaze');
INSERT INTO GROUP07."Abilities" VALUES (158,'Torrent');
INSERT INTO GROUP07."Abilities" VALUES (159,'Torrent');
INSERT INTO GROUP07."Abilities" VALUES (160,'Torrent');
INSERT INTO GROUP07."Abilities" VALUES (161,'Run Away');
INSERT INTO GROUP07."Abilities" VALUES (161,'Keen Eye');
INSERT INTO GROUP07."Abilities" VALUES (162,'Run Away');
INSERT INTO GROUP07."Abilities" VALUES (162,'Keen Eye');
INSERT INTO GROUP07."Abilities" VALUES (163,'Insomnia');
INSERT INTO GROUP07."Abilities" VALUES (163,'Keen Eye');
INSERT INTO GROUP07."Abilities" VALUES (164,'Insomnia');
INSERT INTO GROUP07."Abilities" VALUES (164,'Keen Eye');
INSERT INTO GROUP07."Abilities" VALUES (165,'Swarm');
INSERT INTO GROUP07."Abilities" VALUES (165,'Early Bird');
INSERT INTO GROUP07."Abilities" VALUES (166,'Swarm');
INSERT INTO GROUP07."Abilities" VALUES (166,'Early Bird');
INSERT INTO GROUP07."Abilities" VALUES (167,'Swarm');
INSERT INTO GROUP07."Abilities" VALUES (167,'Insomnia');
INSERT INTO GROUP07."Abilities" VALUES (168,'Swarm');
INSERT INTO GROUP07."Abilities" VALUES (168,'Insomnia');
INSERT INTO GROUP07."Abilities" VALUES (169,'Inner Focus');
INSERT INTO GROUP07."Abilities" VALUES (170,'Volt Absorb');
INSERT INTO GROUP07."Abilities" VALUES (170,'Illuminate');
INSERT INTO GROUP07."Abilities" VALUES (171,'Volt Absorb');
INSERT INTO GROUP07."Abilities" VALUES (171,'Illuminate');
INSERT INTO GROUP07."Abilities" VALUES (172,'Static');
INSERT INTO GROUP07."Abilities" VALUES (173,'Cute Charm');
INSERT INTO GROUP07."Abilities" VALUES (173,'Magic Guard');
INSERT INTO GROUP07."Abilities" VALUES (174,'Cute Charm');
INSERT INTO GROUP07."Abilities" VALUES (174,'Competitive');
INSERT INTO GROUP07."Abilities" VALUES (175,'Hustle');
INSERT INTO GROUP07."Abilities" VALUES (175,'Serene Grace');
INSERT INTO GROUP07."Abilities" VALUES (176,'Hustle');
INSERT INTO GROUP07."Abilities" VALUES (176,'Serene Grace');
INSERT INTO GROUP07."Abilities" VALUES (177,'Synchronize');
INSERT INTO GROUP07."Abilities" VALUES (177,'Early Bird');
INSERT INTO GROUP07."Abilities" VALUES (178,'Synchronize');
INSERT INTO GROUP07."Abilities" VALUES (178,'Early Bird');
INSERT INTO GROUP07."Abilities" VALUES (179,'Static');
INSERT INTO GROUP07."Abilities" VALUES (180,'Static');
INSERT INTO GROUP07."Abilities" VALUES (181,'Static');
INSERT INTO GROUP07."Abilities" VALUES (182,'Chlorophyll');
INSERT INTO GROUP07."Abilities" VALUES (183,'Thick Fat');
INSERT INTO GROUP07."Abilities" VALUES (183,'Huge Power');
INSERT INTO GROUP07."Abilities" VALUES (184,'Thick Fat');
INSERT INTO GROUP07."Abilities" VALUES (184,'Huge Power');
INSERT INTO GROUP07."Abilities" VALUES (185,'Sturdy');
INSERT INTO GROUP07."Abilities" VALUES (185,'Rock Head');
INSERT INTO GROUP07."Abilities" VALUES (186,'Water Absorb');
INSERT INTO GROUP07."Abilities" VALUES (186,'Damp');
INSERT INTO GROUP07."Abilities" VALUES (187,'Chlorophyll');
INSERT INTO GROUP07."Abilities" VALUES (187,'Leaf Guard');
INSERT INTO GROUP07."Abilities" VALUES (188,'Chlorophyll');
INSERT INTO GROUP07."Abilities" VALUES (188,'Leaf Guard');
INSERT INTO GROUP07."Abilities" VALUES (189,'Chlorophyll');
INSERT INTO GROUP07."Abilities" VALUES (189,'Leaf Guard');
INSERT INTO GROUP07."Abilities" VALUES (190,'Run Away');
INSERT INTO GROUP07."Abilities" VALUES (190,'Pickup');
INSERT INTO GROUP07."Abilities" VALUES (191,'Chlorophyll');
INSERT INTO GROUP07."Abilities" VALUES (191,'Solar Power');
INSERT INTO GROUP07."Abilities" VALUES (192,'Chlorophyll');
INSERT INTO GROUP07."Abilities" VALUES (192,'Solar Power');
INSERT INTO GROUP07."Abilities" VALUES (193,'Speed Boost');
INSERT INTO GROUP07."Abilities" VALUES (193,'Compound Eyes');
INSERT INTO GROUP07."Abilities" VALUES (194,'Damp');
INSERT INTO GROUP07."Abilities" VALUES (194,'Water Absorb');
INSERT INTO GROUP07."Abilities" VALUES (195,'Damp');
INSERT INTO GROUP07."Abilities" VALUES (195,'Water Absorb');
INSERT INTO GROUP07."Abilities" VALUES (196,'Synchronize');
INSERT INTO GROUP07."Abilities" VALUES (197,'Synchronize');
INSERT INTO GROUP07."Abilities" VALUES (198,'Insomnia');
INSERT INTO GROUP07."Abilities" VALUES (198,'Super Luck');
INSERT INTO GROUP07."Abilities" VALUES (199,'Oblivious');
INSERT INTO GROUP07."Abilities" VALUES (199,'Own Tempo');
INSERT INTO GROUP07."Abilities" VALUES (200,'Levitate');
INSERT INTO GROUP07."Abilities" VALUES (201,'Levitate');
INSERT INTO GROUP07."Abilities" VALUES (202,'Shadow Tag');
INSERT INTO GROUP07."Abilities" VALUES (203,'Inner Focus');
INSERT INTO GROUP07."Abilities" VALUES (203,'Early Bird');
INSERT INTO GROUP07."Abilities" VALUES (204,'Sturdy');
INSERT INTO GROUP07."Abilities" VALUES (205,'Sturdy');
INSERT INTO GROUP07."Abilities" VALUES (206,'Serene Grace');
INSERT INTO GROUP07."Abilities" VALUES (206,'Run Away');
INSERT INTO GROUP07."Abilities" VALUES (207,'Hyper Cutter');
INSERT INTO GROUP07."Abilities" VALUES (207,'Sand Veil');
INSERT INTO GROUP07."Abilities" VALUES (208,'Rock Head');
INSERT INTO GROUP07."Abilities" VALUES (208,'Sturdy');
INSERT INTO GROUP07."Abilities" VALUES (209,'Intimidate');
INSERT INTO GROUP07."Abilities" VALUES (209,'Run Away');
INSERT INTO GROUP07."Abilities" VALUES (210,'Intimidate');
INSERT INTO GROUP07."Abilities" VALUES (210,'Quick Feet');
INSERT INTO GROUP07."Abilities" VALUES (211,'Poison Point');
INSERT INTO GROUP07."Abilities" VALUES (211,'Swift Swim');
INSERT INTO GROUP07."Abilities" VALUES (212,'Swarm');
INSERT INTO GROUP07."Abilities" VALUES (212,'Technician');
INSERT INTO GROUP07."Abilities" VALUES (213,'Sturdy');
INSERT INTO GROUP07."Abilities" VALUES (213,'Gluttony');
INSERT INTO GROUP07."Abilities" VALUES (214,'Swarm');
INSERT INTO GROUP07."Abilities" VALUES (214,'Guts');
INSERT INTO GROUP07."Abilities" VALUES (215,'Inner Focus');
INSERT INTO GROUP07."Abilities" VALUES (215,'Keen Eye');
INSERT INTO GROUP07."Abilities" VALUES (216,'Pickup');
INSERT INTO GROUP07."Abilities" VALUES (216,'Quick Feet');
INSERT INTO GROUP07."Abilities" VALUES (217,'Guts');
INSERT INTO GROUP07."Abilities" VALUES (217,'Quick Feet');
INSERT INTO GROUP07."Abilities" VALUES (218,'Magma Armor');
INSERT INTO GROUP07."Abilities" VALUES (218,'Flame Body');
INSERT INTO GROUP07."Abilities" VALUES (219,'Magma Armor');
INSERT INTO GROUP07."Abilities" VALUES (219,'Flame Body');
INSERT INTO GROUP07."Abilities" VALUES (220,'Oblivious');
INSERT INTO GROUP07."Abilities" VALUES (220,'Snow Cloak');
INSERT INTO GROUP07."Abilities" VALUES (221,'Oblivious');
INSERT INTO GROUP07."Abilities" VALUES (221,'Snow Cloak');
INSERT INTO GROUP07."Abilities" VALUES (222,'Hustle');
INSERT INTO GROUP07."Abilities" VALUES (222,'Natural Cure');
INSERT INTO GROUP07."Abilities" VALUES (223,'Hustle');
INSERT INTO GROUP07."Abilities" VALUES (223,'Sniper');
INSERT INTO GROUP07."Abilities" VALUES (224,'Suction Cups');
INSERT INTO GROUP07."Abilities" VALUES (224,'Sniper');
INSERT INTO GROUP07."Abilities" VALUES (225,'Vital Spirit');
INSERT INTO GROUP07."Abilities" VALUES (225,'Hustle');
INSERT INTO GROUP07."Abilities" VALUES (226,'Swift Swim');
INSERT INTO GROUP07."Abilities" VALUES (226,'Water Absorb');
INSERT INTO GROUP07."Abilities" VALUES (227,'Keen Eye');
INSERT INTO GROUP07."Abilities" VALUES (227,'Sturdy');
INSERT INTO GROUP07."Abilities" VALUES (228,'Early Bird');
INSERT INTO GROUP07."Abilities" VALUES (228,'Flash Fire');
INSERT INTO GROUP07."Abilities" VALUES (229,'Early Bird');
INSERT INTO GROUP07."Abilities" VALUES (229,'Flash Fire');
INSERT INTO GROUP07."Abilities" VALUES (230,'Swift Swim');
INSERT INTO GROUP07."Abilities" VALUES (230,'Sniper');
INSERT INTO GROUP07."Abilities" VALUES (231,'Pickup');
INSERT INTO GROUP07."Abilities" VALUES (232,'Sturdy');
INSERT INTO GROUP07."Abilities" VALUES (233,'Trace');
INSERT INTO GROUP07."Abilities" VALUES (233,'Download');
INSERT INTO GROUP07."Abilities" VALUES (234,'Intimidate');
INSERT INTO GROUP07."Abilities" VALUES (234,'Frisk');
INSERT INTO GROUP07."Abilities" VALUES (235,'Own Tempo');
INSERT INTO GROUP07."Abilities" VALUES (235,'Technician');
INSERT INTO GROUP07."Abilities" VALUES (236,'Guts');
INSERT INTO GROUP07."Abilities" VALUES (236,'Steadfast');
INSERT INTO GROUP07."Abilities" VALUES (237,'Intimidate');
INSERT INTO GROUP07."Abilities" VALUES (237,'Technician');
INSERT INTO GROUP07."Abilities" VALUES (238,'Oblivious');
INSERT INTO GROUP07."Abilities" VALUES (238,'Forewarn');
INSERT INTO GROUP07."Abilities" VALUES (239,'Static');
INSERT INTO GROUP07."Abilities" VALUES (240,'Flame Body');
INSERT INTO GROUP07."Abilities" VALUES (241,'Thick Fat');
INSERT INTO GROUP07."Abilities" VALUES (241,'Scrappy');
INSERT INTO GROUP07."Abilities" VALUES (242,'Natural Cure');
INSERT INTO GROUP07."Abilities" VALUES (242,'Serene Grace');
INSERT INTO GROUP07."Abilities" VALUES (243,'Pressure');
INSERT INTO GROUP07."Abilities" VALUES (244,'Pressure');
INSERT INTO GROUP07."Abilities" VALUES (245,'Pressure');
INSERT INTO GROUP07."Abilities" VALUES (246,'Guts');
INSERT INTO GROUP07."Abilities" VALUES (247,'Shed Skin');
INSERT INTO GROUP07."Abilities" VALUES (248,'Sand Stream');
INSERT INTO GROUP07."Abilities" VALUES (249,'Pressure');
INSERT INTO GROUP07."Abilities" VALUES (250,'Pressure');
INSERT INTO GROUP07."Abilities" VALUES (251,'Natural Cure');
INSERT INTO GROUP07."Abilities" VALUES (252,'Overgrow');
INSERT INTO GROUP07."Abilities" VALUES (253,'Overgrow');
INSERT INTO GROUP07."Abilities" VALUES (254,'Overgrow');
INSERT INTO GROUP07."Abilities" VALUES (255,'Blaze');
INSERT INTO GROUP07."Abilities" VALUES (256,'Blaze');
INSERT INTO GROUP07."Abilities" VALUES (257,'Blaze');
INSERT INTO GROUP07."Abilities" VALUES (258,'Torrent');
INSERT INTO GROUP07."Abilities" VALUES (259,'Torrent');
INSERT INTO GROUP07."Abilities" VALUES (260,'Torrent');
INSERT INTO GROUP07."Abilities" VALUES (261,'Run Away');
INSERT INTO GROUP07."Abilities" VALUES (261,'Quick Feet');
INSERT INTO GROUP07."Abilities" VALUES (262,'Intimidate');
INSERT INTO GROUP07."Abilities" VALUES (262,'Quick Feet');
INSERT INTO GROUP07."Abilities" VALUES (263,'Pickup');
INSERT INTO GROUP07."Abilities" VALUES (263,'Gluttony');
INSERT INTO GROUP07."Abilities" VALUES (264,'Pickup');
INSERT INTO GROUP07."Abilities" VALUES (264,'Gluttony');
INSERT INTO GROUP07."Abilities" VALUES (265,'Shield Dust');
INSERT INTO GROUP07."Abilities" VALUES (266,'Shed Skin');
INSERT INTO GROUP07."Abilities" VALUES (267,'Swarm');
INSERT INTO GROUP07."Abilities" VALUES (268,'Shed Skin');
INSERT INTO GROUP07."Abilities" VALUES (269,'Shield Dust');
INSERT INTO GROUP07."Abilities" VALUES (270,'Swift Swim');
INSERT INTO GROUP07."Abilities" VALUES (270,'Rain Dish');
INSERT INTO GROUP07."Abilities" VALUES (271,'Swift Swim');
INSERT INTO GROUP07."Abilities" VALUES (271,'Rain Dish');
INSERT INTO GROUP07."Abilities" VALUES (272,'Swift Swim');
INSERT INTO GROUP07."Abilities" VALUES (272,'Rain Dish');
INSERT INTO GROUP07."Abilities" VALUES (273,'Chlorophyll');
INSERT INTO GROUP07."Abilities" VALUES (273,'Early Bird');
INSERT INTO GROUP07."Abilities" VALUES (274,'Chlorophyll');
INSERT INTO GROUP07."Abilities" VALUES (274,'Early Bird');
INSERT INTO GROUP07."Abilities" VALUES (275,'Chlorophyll');
INSERT INTO GROUP07."Abilities" VALUES (275,'Early Bird');
INSERT INTO GROUP07."Abilities" VALUES (276,'Guts');
INSERT INTO GROUP07."Abilities" VALUES (277,'Guts');
INSERT INTO GROUP07."Abilities" VALUES (278,'Keen Eye');
INSERT INTO GROUP07."Abilities" VALUES (278,'Hydration');
INSERT INTO GROUP07."Abilities" VALUES (279,'Keen Eye');
INSERT INTO GROUP07."Abilities" VALUES (279,'Drizzle');
INSERT INTO GROUP07."Abilities" VALUES (280,'Synchronize');
INSERT INTO GROUP07."Abilities" VALUES (280,'Trace');
INSERT INTO GROUP07."Abilities" VALUES (281,'Synchronize');
INSERT INTO GROUP07."Abilities" VALUES (281,'Trace');
INSERT INTO GROUP07."Abilities" VALUES (282,'Synchronize');
INSERT INTO GROUP07."Abilities" VALUES (282,'Trace');
INSERT INTO GROUP07."Abilities" VALUES (283,'Swift Swim');
INSERT INTO GROUP07."Abilities" VALUES (284,'Intimidate');
INSERT INTO GROUP07."Abilities" VALUES (285,'Effect Spore');
INSERT INTO GROUP07."Abilities" VALUES (285,'Poison Heal');
INSERT INTO GROUP07."Abilities" VALUES (286,'Effect Spore');
INSERT INTO GROUP07."Abilities" VALUES (286,'Poison Heal');
INSERT INTO GROUP07."Abilities" VALUES (287,'Truant');
INSERT INTO GROUP07."Abilities" VALUES (288,'Vital Spirit');
INSERT INTO GROUP07."Abilities" VALUES (289,'Truant');
INSERT INTO GROUP07."Abilities" VALUES (290,'Compound Eyes');
INSERT INTO GROUP07."Abilities" VALUES (291,'Speed Boost');
INSERT INTO GROUP07."Abilities" VALUES (292,'Wonder Guard');
INSERT INTO GROUP07."Abilities" VALUES (293,'Soundproof');
INSERT INTO GROUP07."Abilities" VALUES (294,'Soundproof');
INSERT INTO GROUP07."Abilities" VALUES (295,'Soundproof');
INSERT INTO GROUP07."Abilities" VALUES (296,'Thick Fat');
INSERT INTO GROUP07."Abilities" VALUES (296,'Guts');
INSERT INTO GROUP07."Abilities" VALUES (297,'Thick Fat');
INSERT INTO GROUP07."Abilities" VALUES (297,'Guts');
INSERT INTO GROUP07."Abilities" VALUES (298,'Thick Fat');
INSERT INTO GROUP07."Abilities" VALUES (298,'Huge Power');
INSERT INTO GROUP07."Abilities" VALUES (299,'Sturdy');
INSERT INTO GROUP07."Abilities" VALUES (299,'Magnet Pull');
INSERT INTO GROUP07."Abilities" VALUES (300,'Cute Charm');
INSERT INTO GROUP07."Abilities" VALUES (300,'Normalize');
INSERT INTO GROUP07."Abilities" VALUES (301,'Cute Charm');
INSERT INTO GROUP07."Abilities" VALUES (301,'Normalize');
INSERT INTO GROUP07."Abilities" VALUES (302,'Keen Eye');
INSERT INTO GROUP07."Abilities" VALUES (302,'Stall');
INSERT INTO GROUP07."Abilities" VALUES (303,'Hyper Cutter');
INSERT INTO GROUP07."Abilities" VALUES (303,'Intimidate');
INSERT INTO GROUP07."Abilities" VALUES (304,'Sturdy');
INSERT INTO GROUP07."Abilities" VALUES (304,'Rock Head');
INSERT INTO GROUP07."Abilities" VALUES (305,'Sturdy');
INSERT INTO GROUP07."Abilities" VALUES (305,'Rock Head');
INSERT INTO GROUP07."Abilities" VALUES (306,'Sturdy');
INSERT INTO GROUP07."Abilities" VALUES (306,'Rock Head');
INSERT INTO GROUP07."Abilities" VALUES (307,'Pure Power');
INSERT INTO GROUP07."Abilities" VALUES (308,'Pure Power');
INSERT INTO GROUP07."Abilities" VALUES (309,'Static');
INSERT INTO GROUP07."Abilities" VALUES (309,'Lightning Rod');
INSERT INTO GROUP07."Abilities" VALUES (310,'Static');
INSERT INTO GROUP07."Abilities" VALUES (310,'Lightning Rod');
INSERT INTO GROUP07."Abilities" VALUES (311,'Plus');
INSERT INTO GROUP07."Abilities" VALUES (312,'Minus');
INSERT INTO GROUP07."Abilities" VALUES (313,'Illuminate');
INSERT INTO GROUP07."Abilities" VALUES (313,'Swarm');
INSERT INTO GROUP07."Abilities" VALUES (314,'Oblivious');
INSERT INTO GROUP07."Abilities" VALUES (314,'Tinted Lens');
INSERT INTO GROUP07."Abilities" VALUES (315,'Natural Cure');
INSERT INTO GROUP07."Abilities" VALUES (315,'Poison Point');
INSERT INTO GROUP07."Abilities" VALUES (316,'Liquid Ooze');
INSERT INTO GROUP07."Abilities" VALUES (316,'Sticky Hold');
INSERT INTO GROUP07."Abilities" VALUES (317,'Liquid Ooze');
INSERT INTO GROUP07."Abilities" VALUES (317,'Sticky Hold');
INSERT INTO GROUP07."Abilities" VALUES (318,'Rough Skin');
INSERT INTO GROUP07."Abilities" VALUES (319,'Rough Skin');
INSERT INTO GROUP07."Abilities" VALUES (320,'Water Veil');
INSERT INTO GROUP07."Abilities" VALUES (320,'Oblivious');
INSERT INTO GROUP07."Abilities" VALUES (321,'Water Veil');
INSERT INTO GROUP07."Abilities" VALUES (321,'Oblivious');
INSERT INTO GROUP07."Abilities" VALUES (322,'Oblivious');
INSERT INTO GROUP07."Abilities" VALUES (322,'Simple');
INSERT INTO GROUP07."Abilities" VALUES (323,'Magma Armor');
INSERT INTO GROUP07."Abilities" VALUES (323,'Solid Rock');
INSERT INTO GROUP07."Abilities" VALUES (324,'White Smoke');
INSERT INTO GROUP07."Abilities" VALUES (324,'Drought');
INSERT INTO GROUP07."Abilities" VALUES (325,'Thick Fat');
INSERT INTO GROUP07."Abilities" VALUES (325,'Own Tempo');
INSERT INTO GROUP07."Abilities" VALUES (326,'Thick Fat');
INSERT INTO GROUP07."Abilities" VALUES (326,'Own Tempo');
INSERT INTO GROUP07."Abilities" VALUES (327,'Own Tempo');
INSERT INTO GROUP07."Abilities" VALUES (327,'Tangled Feet');
INSERT INTO GROUP07."Abilities" VALUES (328,'Hyper Cutter');
INSERT INTO GROUP07."Abilities" VALUES (328,'Arena Trap');
INSERT INTO GROUP07."Abilities" VALUES (329,'Levitate');
INSERT INTO GROUP07."Abilities" VALUES (330,'Levitate');
INSERT INTO GROUP07."Abilities" VALUES (331,'Sand Veil');
INSERT INTO GROUP07."Abilities" VALUES (332,'Sand Veil');
INSERT INTO GROUP07."Abilities" VALUES (333,'Natural Cure');
INSERT INTO GROUP07."Abilities" VALUES (334,'Natural Cure');
INSERT INTO GROUP07."Abilities" VALUES (335,'Immunity');
INSERT INTO GROUP07."Abilities" VALUES (336,'Shed Skin');
INSERT INTO GROUP07."Abilities" VALUES (337,'Levitate');
INSERT INTO GROUP07."Abilities" VALUES (338,'Levitate');
INSERT INTO GROUP07."Abilities" VALUES (339,'Oblivious');
INSERT INTO GROUP07."Abilities" VALUES (339,'Anticipation');
INSERT INTO GROUP07."Abilities" VALUES (340,'Oblivious');
INSERT INTO GROUP07."Abilities" VALUES (340,'Anticipation');
INSERT INTO GROUP07."Abilities" VALUES (341,'Hyper Cutter');
INSERT INTO GROUP07."Abilities" VALUES (341,'Shell Armor');
INSERT INTO GROUP07."Abilities" VALUES (342,'Hyper Cutter');
INSERT INTO GROUP07."Abilities" VALUES (342,'Shell Armor');
INSERT INTO GROUP07."Abilities" VALUES (343,'Levitate');
INSERT INTO GROUP07."Abilities" VALUES (344,'Levitate');
INSERT INTO GROUP07."Abilities" VALUES (345,'Suction Cups');
INSERT INTO GROUP07."Abilities" VALUES (346,'Suction Cups');
INSERT INTO GROUP07."Abilities" VALUES (347,'Battle Armor');
INSERT INTO GROUP07."Abilities" VALUES (348,'Battle Armor');
INSERT INTO GROUP07."Abilities" VALUES (349,'Swift Swim');
INSERT INTO GROUP07."Abilities" VALUES (349,'Oblivious');
INSERT INTO GROUP07."Abilities" VALUES (350,'Marvel Scale');
INSERT INTO GROUP07."Abilities" VALUES (350,'Competitive');
INSERT INTO GROUP07."Abilities" VALUES (351,'Forecast');
INSERT INTO GROUP07."Abilities" VALUES (352,'Color Change');
INSERT INTO GROUP07."Abilities" VALUES (353,'Insomnia');
INSERT INTO GROUP07."Abilities" VALUES (353,'Frisk');
INSERT INTO GROUP07."Abilities" VALUES (354,'Insomnia');
INSERT INTO GROUP07."Abilities" VALUES (354,'Frisk');
INSERT INTO GROUP07."Abilities" VALUES (355,'Levitate');
INSERT INTO GROUP07."Abilities" VALUES (356,'Pressure');
INSERT INTO GROUP07."Abilities" VALUES (357,'Chlorophyll');
INSERT INTO GROUP07."Abilities" VALUES (357,'Solar Power');
INSERT INTO GROUP07."Abilities" VALUES (358,'Levitate');
INSERT INTO GROUP07."Abilities" VALUES (359,'Pressure');
INSERT INTO GROUP07."Abilities" VALUES (359,'Super Luck');
INSERT INTO GROUP07."Abilities" VALUES (360,'Shadow Tag');
INSERT INTO GROUP07."Abilities" VALUES (361,'Inner Focus');
INSERT INTO GROUP07."Abilities" VALUES (361,'Ice Body');
INSERT INTO GROUP07."Abilities" VALUES (362,'Inner Focus');
INSERT INTO GROUP07."Abilities" VALUES (362,'Ice Body');
INSERT INTO GROUP07."Abilities" VALUES (363,'Thick Fat');
INSERT INTO GROUP07."Abilities" VALUES (363,'Ice Body');
INSERT INTO GROUP07."Abilities" VALUES (364,'Thick Fat');
INSERT INTO GROUP07."Abilities" VALUES (364,'Ice Body');
INSERT INTO GROUP07."Abilities" VALUES (365,'Thick Fat');
INSERT INTO GROUP07."Abilities" VALUES (365,'Ice Body');
INSERT INTO GROUP07."Abilities" VALUES (366,'Shell Armor');
INSERT INTO GROUP07."Abilities" VALUES (367,'Swift Swim');
INSERT INTO GROUP07."Abilities" VALUES (368,'Swift Swim');
INSERT INTO GROUP07."Abilities" VALUES (369,'Swift Swim');
INSERT INTO GROUP07."Abilities" VALUES (369,'Rock Head');
INSERT INTO GROUP07."Abilities" VALUES (370,'Swift Swim');
INSERT INTO GROUP07."Abilities" VALUES (371,'Rock Head');
INSERT INTO GROUP07."Abilities" VALUES (372,'Rock Head');
INSERT INTO GROUP07."Abilities" VALUES (373,'Intimidate');
INSERT INTO GROUP07."Abilities" VALUES (374,'Clear Body');
INSERT INTO GROUP07."Abilities" VALUES (375,'Clear Body');
INSERT INTO GROUP07."Abilities" VALUES (376,'Clear Body');
INSERT INTO GROUP07."Abilities" VALUES (377,'Clear Body');
INSERT INTO GROUP07."Abilities" VALUES (378,'Clear Body');
INSERT INTO GROUP07."Abilities" VALUES (379,'Clear Body');
INSERT INTO GROUP07."Abilities" VALUES (380,'Levitate');
INSERT INTO GROUP07."Abilities" VALUES (381,'Levitate');
INSERT INTO GROUP07."Abilities" VALUES (382,'Drizzle');
INSERT INTO GROUP07."Abilities" VALUES (383,'Drought');
INSERT INTO GROUP07."Abilities" VALUES (384,'Air Lock');
INSERT INTO GROUP07."Abilities" VALUES (385,'Serene Grace');
INSERT INTO GROUP07."Abilities" VALUES (386,'Pressure');
