INSERT INTO GROUP07."HM" VALUES ('Cut',1);
INSERT INTO GROUP07."HM" VALUES ('Dive',8);
INSERT INTO GROUP07."HM" VALUES ('Flash',5);
INSERT INTO GROUP07."HM" VALUES ('Fly',2);
INSERT INTO GROUP07."HM" VALUES ('Rock Smash',6);
INSERT INTO GROUP07."HM" VALUES ('Strength',4);
INSERT INTO GROUP07."HM" VALUES ('Surf',3);
INSERT INTO GROUP07."HM" VALUES ('Waterfall',7);
