INSERT INTO GROUP07."Location" VALUES ('Abandoned Ship');
INSERT INTO GROUP07."Location" VALUES ('Altering Cave');
INSERT INTO GROUP07."Location" VALUES ('Ancient Tomb');
INSERT INTO GROUP07."Location" VALUES ('Artisan Cave');
INSERT INTO GROUP07."Location" VALUES ('Battle Arena');
INSERT INTO GROUP07."Location" VALUES ('Battle Dome');
INSERT INTO GROUP07."Location" VALUES ('Battle Factory');
INSERT INTO GROUP07."Location" VALUES ('Battle Frontier');
INSERT INTO GROUP07."Location" VALUES ('Battle Palace');
INSERT INTO GROUP07."Location" VALUES ('Battle Pike');
INSERT INTO GROUP07."Location" VALUES ('Battle Pyramid');
INSERT INTO GROUP07."Location" VALUES ('Battle Tower');
INSERT INTO GROUP07."Location" VALUES ('Birth Island');
INSERT INTO GROUP07."Location" VALUES ('Cave of Origin');
INSERT INTO GROUP07."Location" VALUES ('Cove Lily Motel');
INSERT INTO GROUP07."Location" VALUES ('Desert Ruins');
INSERT INTO GROUP07."Location" VALUES ('Desert Underpass');
INSERT INTO GROUP07."Location" VALUES ('Devon Corporation');
INSERT INTO GROUP07."Location" VALUES ('Dewford Town');
INSERT INTO GROUP07."Location" VALUES ('Ever Grande City');
INSERT INTO GROUP07."Location" VALUES ('Fallarbor Town');
INSERT INTO GROUP07."Location" VALUES ('Fiery Path');
INSERT INTO GROUP07."Location" VALUES ('Fortree City');
INSERT INTO GROUP07."Location" VALUES ('Granite Cave');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 101');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 102');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 103');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 104');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 105');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 106');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 107');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 108');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 109');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 110');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 111');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 112');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 113');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 114');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 115');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 116');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 117');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 118');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 119');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 120');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 121');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 122');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 123');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 124');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 125');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 126');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 127');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 128');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 129');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 130');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 131');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 132');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 133');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Route 134');
INSERT INTO GROUP07."Location" VALUES ('Hoenn Safari Zone');
INSERT INTO GROUP07."Location" VALUES ('Island Cave');
INSERT INTO GROUP07."Location" VALUES ('Jagged Pass');
INSERT INTO GROUP07."Location" VALUES ('Lavaridge Town');
INSERT INTO GROUP07."Location" VALUES ('Lilycove City');
INSERT INTO GROUP07."Location" VALUES ('Lilycove Department Store');
INSERT INTO GROUP07."Location" VALUES ('Lilycove Museum');
INSERT INTO GROUP07."Location" VALUES ('Littleroot Town');
INSERT INTO GROUP07."Location" VALUES ('Magma Hideout (Jagged Pass)');
INSERT INTO GROUP07."Location" VALUES ('Marine Cave');
INSERT INTO GROUP07."Location" VALUES ('Mauville City');
INSERT INTO GROUP07."Location" VALUES ('Mauville Game Corner');
INSERT INTO GROUP07."Location" VALUES ('Meteor Falls');
INSERT INTO GROUP07."Location" VALUES ('Mirage Island (Generation III)');
INSERT INTO GROUP07."Location" VALUES ('Mirage Tower');
INSERT INTO GROUP07."Location" VALUES ('Mossdeep City');
INSERT INTO GROUP07."Location" VALUES ('Mossdeep Space Center');
INSERT INTO GROUP07."Location" VALUES ('Mt. Chimney');
INSERT INTO GROUP07."Location" VALUES ('Mt. Pyre');
INSERT INTO GROUP07."Location" VALUES ('New Mauville');
INSERT INTO GROUP07."Location" VALUES ('Oceanic Museum');
INSERT INTO GROUP07."Location" VALUES ('Oldale Town');
INSERT INTO GROUP07."Location" VALUES ('Pacifidlog Town');
INSERT INTO GROUP07."Location" VALUES ('Petalburg City');
INSERT INTO GROUP07."Location" VALUES ('Petalburg Woods');
INSERT INTO GROUP07."Location" VALUES ('Rustboro City');
INSERT INTO GROUP07."Location" VALUES ('Rusturf Tunnel');
INSERT INTO GROUP07."Location" VALUES ('Rydel's Cycles');
INSERT INTO GROUP07."Location" VALUES ('S.S. Tidal');
INSERT INTO GROUP07."Location" VALUES ('Scorched Slab');
INSERT INTO GROUP07."Location" VALUES ('Seafloor Cavern');
INSERT INTO GROUP07."Location" VALUES ('Sealed Chamber');
INSERT INTO GROUP07."Location" VALUES ('Seaside Cycling Road');
INSERT INTO GROUP07."Location" VALUES ('Shoal Cave');
INSERT INTO GROUP07."Location" VALUES ('Sky Pillar');
INSERT INTO GROUP07."Location" VALUES ('Slateport City');
INSERT INTO GROUP07."Location" VALUES ('Sootopolis City');
INSERT INTO GROUP07."Location" VALUES ('Southern Island');
INSERT INTO GROUP07."Location" VALUES ('Stern's Shipyard');
INSERT INTO GROUP07."Location" VALUES ('Submarine Explorer 1');
INSERT INTO GROUP07."Location" VALUES ('Team Aqua Hideout');
INSERT INTO GROUP07."Location" VALUES ('Terra Cave');
INSERT INTO GROUP07."Location" VALUES ('Trainer Hill');
INSERT INTO GROUP07."Location" VALUES ('Trick House');
INSERT INTO GROUP07."Location" VALUES ('Underwater');
INSERT INTO GROUP07."Location" VALUES ('Verdanturf Town');
INSERT INTO GROUP07."Location" VALUES ('Victory Road (Hoenn)');
INSERT INTO GROUP07."Location" VALUES ('Weather Institute');
