INSERT INTO GROUP07."Trainer" VALUES ( 1,'Thalia','Beauty');
INSERT INTO GROUP07."Trainer" VALUES ( 2,'Demetrius','Youngster');
INSERT INTO GROUP07."Trainer" VALUES ( 3,'Duncan','Sailor');
INSERT INTO GROUP07."Trainer" VALUES ( 4,'Charlie','Tuber');
INSERT INTO GROUP07."Trainer" VALUES ( 5,'Garrison','Ruin Maniac');
INSERT INTO GROUP07."Trainer" VALUES ( 6,'Jani','Tuber');
INSERT INTO GROUP07."Trainer" VALUES ( 7,'Kira & Dan','Young Couple');
INSERT INTO GROUP07."Trainer" VALUES ( 8,'Sidney','Elite Four');
INSERT INTO GROUP07."Trainer" VALUES ( 9,'Phoebe','Elite Four');
INSERT INTO GROUP07."Trainer" VALUES (10,'Glacia','Elite Four');
INSERT INTO GROUP07."Trainer" VALUES (11,'Drake','Elite Four');
INSERT INTO GROUP07."Trainer" VALUES (12,'Wallace','Champion');
INSERT INTO GROUP07."Trainer" VALUES (13,'Calvin','Youngster');
INSERT INTO GROUP07."Trainer" VALUES (14,'Rick','Bug Catcher');
INSERT INTO GROUP07."Trainer" VALUES (15,'Allen','Youngster');
INSERT INTO GROUP07."Trainer" VALUES (16,'Tiana','Lass');
INSERT INTO GROUP07."Trainer" VALUES (17,'Brendan','Pokémon Trainer');
INSERT INTO GROUP07."Trainer" VALUES (18,'May','Pokémon Trainer');
INSERT INTO GROUP07."Trainer" VALUES (19,'Isabelle','Swimmer♀');
INSERT INTO GROUP07."Trainer" VALUES (20,'Pete','Swimmer♂');
INSERT INTO GROUP07."Trainer" VALUES (21,'Daisy','Aroma Lady');
INSERT INTO GROUP07."Trainer" VALUES (22,'Amy & Liv','Twins');
INSERT INTO GROUP07."Trainer" VALUES (23,'Miguel','Pokéfan');
INSERT INTO GROUP07."Trainer" VALUES (24,'Andrew','Fisherman');
INSERT INTO GROUP07."Trainer" VALUES (25,'Rhett','Black Belt');
INSERT INTO GROUP07."Trainer" VALUES (26,'Marcos','Guitarist');
INSERT INTO GROUP07."Trainer" VALUES (27,'Imani','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (28,'Dominik','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (29,'Foster','Ruin Maniac');
INSERT INTO GROUP07."Trainer" VALUES (30,'Beverly','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (31,'Andres','Ruin Maniac');
INSERT INTO GROUP07."Trainer" VALUES (32,'Josue','Bird Keeper');
INSERT INTO GROUP07."Trainer" VALUES (33,'Luis','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (34,'Ned','Fisherman');
INSERT INTO GROUP07."Trainer" VALUES (35,'Elliot','Fisherman');
INSERT INTO GROUP07."Trainer" VALUES (36,'Douglas','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (37,'Kyla','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (38,'Denise','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (39,'Tony','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (40,'Lisa & Ray','Sis and Bro');
INSERT INTO GROUP07."Trainer" VALUES (41,'Darrin','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (42,'Beth','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (43,'Camron','Triathlete');
INSERT INTO GROUP07."Trainer" VALUES (44,'Missy','Swimmer♀');
INSERT INTO GROUP07."Trainer" VALUES (45,'Matthew','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (46,'Tara','Swimmer♀');
INSERT INTO GROUP07."Trainer" VALUES (47,'Carolina','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (48,'Cory','Sailor');
INSERT INTO GROUP07."Trainer" VALUES (49,'Jerome','Swimmer♂');
INSERT INTO GROUP07."Trainer" VALUES (50,'Huey','Sailor');
INSERT INTO GROUP07."Trainer" VALUES (51,'Edmond','Sailor');
INSERT INTO GROUP07."Trainer" VALUES (52,'Hailey','Tuber');
INSERT INTO GROUP07."Trainer" VALUES (53,'Ricky','Tuber');
INSERT INTO GROUP07."Trainer" VALUES (54,'Lola','Tuber');
INSERT INTO GROUP07."Trainer" VALUES (55,'Chandler','Tuber');
INSERT INTO GROUP07."Trainer" VALUES (56,'Simon','Tuber');
INSERT INTO GROUP07."Trainer" VALUES (57,'Johanna','Beauty');
INSERT INTO GROUP07."Trainer" VALUES (58,'Dwayne','Sailor');
INSERT INTO GROUP07."Trainer" VALUES (59,'Austina','Tuber');
INSERT INTO GROUP07."Trainer" VALUES (60,'Gwen','Tuber');
INSERT INTO GROUP07."Trainer" VALUES (61,'David','Swimmer♂');
INSERT INTO GROUP07."Trainer" VALUES (62,'Alice','Swimmer♀');
INSERT INTO GROUP07."Trainer" VALUES (63,'Carter','Fisherman');
INSERT INTO GROUP07."Trainer" VALUES (64,'Elijah','Bird Keeper');
INSERT INTO GROUP07."Trainer" VALUES (65,'Mel & Paul','Young Couple');
INSERT INTO GROUP07."Trainer" VALUES (66,'Isabel','Pokéfan');
INSERT INTO GROUP07."Trainer" VALUES (67,'Kaleb','Pokéfan');
INSERT INTO GROUP07."Trainer" VALUES (68,'Timmy','Youngster');
INSERT INTO GROUP07."Trainer" VALUES (69,'Edwin','Collector');
INSERT INTO GROUP07."Trainer" VALUES (70,'Joseph','Guitarist');
INSERT INTO GROUP07."Trainer" VALUES (71,'Edward','Psychic');
INSERT INTO GROUP07."Trainer" VALUES (72,'Alyssa','Triathlete');
INSERT INTO GROUP07."Trainer" VALUES (73,'Dale','Fisherman');
INSERT INTO GROUP07."Trainer" VALUES (74,'Victor','Winstrate');
INSERT INTO GROUP07."Trainer" VALUES (75,'Victoria','Winstrate');
INSERT INTO GROUP07."Trainer" VALUES (76,'Vivi','Winstrate');
INSERT INTO GROUP07."Trainer" VALUES (77,'Vicky','Winstrate');
INSERT INTO GROUP07."Trainer" VALUES (78,'Tyron','Camper');
INSERT INTO GROUP07."Trainer" VALUES (79,'Celina','Aroma Lady');
INSERT INTO GROUP07."Trainer" VALUES (80,'Bianca','Picnicker');
INSERT INTO GROUP07."Trainer" VALUES (81,'Hayden','Kindler');
INSERT INTO GROUP07."Trainer" VALUES (82,'Gabby and Ty','Interviewer');
INSERT INTO GROUP07."Trainer" VALUES (83,'Irene','Picnicker');
INSERT INTO GROUP07."Trainer" VALUES (84,'Travis','Camper');
INSERT INTO GROUP07."Trainer" VALUES (85,'Heidi','Picnicker');
INSERT INTO GROUP07."Trainer" VALUES (86,'Beau','Camper');
INSERT INTO GROUP07."Trainer" VALUES (87,'Drew','Camper');
INSERT INTO GROUP07."Trainer" VALUES (88,'Becky','Picnicker');
INSERT INTO GROUP07."Trainer" VALUES (89,'Dusty','Ruin Maniac');
INSERT INTO GROUP07."Trainer" VALUES (90,'Celia','Picnicker');
INSERT INTO GROUP07."Trainer" VALUES (91,'Bryan','Ruin Maniac');
INSERT INTO GROUP07."Trainer" VALUES (92,'Branden','Camper');
INSERT INTO GROUP07."Trainer" VALUES (93,'Wilton','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (94,'Brooke','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (95,'Daisuke','Black Belt');
INSERT INTO GROUP07."Trainer" VALUES (96,'Larry','Camper');
INSERT INTO GROUP07."Trainer" VALUES (97,'Carol','Picnicker');
INSERT INTO GROUP07."Trainer" VALUES (98,'Trent','Hiker');
INSERT INTO GROUP07."Trainer" VALUES (99,'Brice','Hiker');
INSERT INTO GROUP07."Trainer" VALUES (100,'Bryant','Kindler');
INSERT INTO GROUP07."Trainer" VALUES (101,'Shayla','Aroma Lady');
INSERT INTO GROUP07."Trainer" VALUES (102,'Jaylen','Youngster');
INSERT INTO GROUP07."Trainer" VALUES (103,'Lawrence','Camper');
INSERT INTO GROUP07."Trainer" VALUES (104,'Lung','Ninja Boy');
INSERT INTO GROUP07."Trainer" VALUES (105,'Wyatt','PokéManiac');
INSERT INTO GROUP07."Trainer" VALUES (106,'Madeline','Parasol Lady');
INSERT INTO GROUP07."Trainer" VALUES (107,'Tori & Tia','Twins');
INSERT INTO GROUP07."Trainer" VALUES (108,'Lao','Ninja Boy');
INSERT INTO GROUP07."Trainer" VALUES (109,'Dillon','Youngster');
INSERT INTO GROUP07."Trainer" VALUES (110,'Sophie','Picnicker');
INSERT INTO GROUP07."Trainer" VALUES (111,'Coby','Bird Keeper');
INSERT INTO GROUP07."Trainer" VALUES (112,'Nolan','Fisherman');
INSERT INTO GROUP07."Trainer" VALUES (113,'Charlotte','Picnicker');
INSERT INTO GROUP07."Trainer" VALUES (114,'Kai','Fisherman');
INSERT INTO GROUP07."Trainer" VALUES (115,'Claude','Fisherman');
INSERT INTO GROUP07."Trainer" VALUES (116,'Nancy','Picnicker');
INSERT INTO GROUP07."Trainer" VALUES (117,'Tyra & Ivy','Sr. and Jr.');
INSERT INTO GROUP07."Trainer" VALUES (118,'Shane','Camper');
INSERT INTO GROUP07."Trainer" VALUES (119,'Steve','PokéManiac');
INSERT INTO GROUP07."Trainer" VALUES (120,'Bernie','Kindler');
INSERT INTO GROUP07."Trainer" VALUES (121,'Lucas','Hiker');
INSERT INTO GROUP07."Trainer" VALUES (122,'Angelina','Picnicker');
INSERT INTO GROUP07."Trainer" VALUES (123,'Lenny','Hiker');
INSERT INTO GROUP07."Trainer" VALUES (124,'Nob','Black Belt');
INSERT INTO GROUP07."Trainer" VALUES (125,'Hector','Collector');
INSERT INTO GROUP07."Trainer" VALUES (126,'Marlene','Psychic');
INSERT INTO GROUP07."Trainer" VALUES (127,'Cyndy','Battle Girl');
INSERT INTO GROUP07."Trainer" VALUES (128,'Jaiden','Ninja Boy');
INSERT INTO GROUP07."Trainer" VALUES (129,'Timothy','Expert');
INSERT INTO GROUP07."Trainer" VALUES (130,'Kyra','Triathlete');
INSERT INTO GROUP07."Trainer" VALUES (131,'Koichi','Black Belt');
INSERT INTO GROUP07."Trainer" VALUES (132,'Helene','Battle Girl');
INSERT INTO GROUP07."Trainer" VALUES (133,'Alix','Psychic');
INSERT INTO GROUP07."Trainer" VALUES (134,'Jose','Bug Catcher');
INSERT INTO GROUP07."Trainer" VALUES (135,'Joey','Youngster');
INSERT INTO GROUP07."Trainer" VALUES (136,'Karen','School Kid');
INSERT INTO GROUP07."Trainer" VALUES (137,'Clark','Hiker');
INSERT INTO GROUP07."Trainer" VALUES (138,'Johnson','Youngster');
INSERT INTO GROUP07."Trainer" VALUES (139,'Devan','Hiker');
INSERT INTO GROUP07."Trainer" VALUES (140,'Sarah','Lady');
INSERT INTO GROUP07."Trainer" VALUES (141,'Dawson','Rich Boy');
INSERT INTO GROUP07."Trainer" VALUES (142,'Jerry','School Kid');
INSERT INTO GROUP07."Trainer" VALUES (143,'Janice','Lass');
INSERT INTO GROUP07."Trainer" VALUES (144,'Dylan','Triathlete');
INSERT INTO GROUP07."Trainer" VALUES (145,'Anna & Meg','Sr. and Jr.');
INSERT INTO GROUP07."Trainer" VALUES (146,'Isaac','Pokémon Breeder');
INSERT INTO GROUP07."Trainer" VALUES (147,'Maria','Triathlete');
INSERT INTO GROUP07."Trainer" VALUES (148,'Derek','Bug Maniac');
INSERT INTO GROUP07."Trainer" VALUES (149,'Brandi','Psychic');
INSERT INTO GROUP07."Trainer" VALUES (150,'Melina','Triathlete');
INSERT INTO GROUP07."Trainer" VALUES (151,'Aisha','Battle Girl');
INSERT INTO GROUP07."Trainer" VALUES (152,'Lydia','Pokémon Breeder');
INSERT INTO GROUP07."Trainer" VALUES (153,'Rose','Aroma Lady');
INSERT INTO GROUP07."Trainer" VALUES (154,'Deandre','Youngster');
INSERT INTO GROUP07."Trainer" VALUES (155,'Wade','Fisherman');
INSERT INTO GROUP07."Trainer" VALUES (156,'Dalton','Guitarist');
INSERT INTO GROUP07."Trainer" VALUES (157,'Barny','Fisherman');
INSERT INTO GROUP07."Trainer" VALUES (158,'Chester','Bird Keeper');
INSERT INTO GROUP07."Trainer" VALUES (159,'Perry','Bird Keeper');
INSERT INTO GROUP07."Trainer" VALUES (160,'Kent','Bug Catcher');
INSERT INTO GROUP07."Trainer" VALUES (161,'Donald','Bug Maniac');
INSERT INTO GROUP07."Trainer" VALUES (162,'Greg','Bug Catcher');
INSERT INTO GROUP07."Trainer" VALUES (163,'Taylor','Bug Maniac');
INSERT INTO GROUP07."Trainer" VALUES (164,'Doug','Bug Catcher');
INSERT INTO GROUP07."Trainer" VALUES (165,'Brent','Bug Maniac');
INSERT INTO GROUP07."Trainer" VALUES (166,'Chris','Fisherman');
INSERT INTO GROUP07."Trainer" VALUES (167,'Catherine','Pokémon Ranger');
INSERT INTO GROUP07."Trainer" VALUES (168,'Jackson','Pokémon Ranger');
INSERT INTO GROUP07."Trainer" VALUES (169,'Rachel','Parasol Lady');
INSERT INTO GROUP07."Trainer" VALUES (170,'Phil','Bird Keeper');
INSERT INTO GROUP07."Trainer" VALUES (171,'Takashi','Ninja Boy');
INSERT INTO GROUP07."Trainer" VALUES (172,'Dayton','Kindler');
INSERT INTO GROUP07."Trainer" VALUES (173,'Hugh','Bird Keeper');
INSERT INTO GROUP07."Trainer" VALUES (174,'Fabian','Guitarist');
INSERT INTO GROUP07."Trainer" VALUES (175,'Yasu','Ninja Boy');
INSERT INTO GROUP07."Trainer" VALUES (176,'Hideo','Ninja Boy');
INSERT INTO GROUP07."Trainer" VALUES (177,'Clarissa','Parasol Lady');
INSERT INTO GROUP07."Trainer" VALUES (178,'Robert','Bird Keeper');
INSERT INTO GROUP07."Trainer" VALUES (179,'Colin','Bird Keeper');
INSERT INTO GROUP07."Trainer" VALUES (180,'Leonel','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (181,'Angelica','Parasol Lady');
INSERT INTO GROUP07."Trainer" VALUES (182,'Riley','Ninja Boy');
INSERT INTO GROUP07."Trainer" VALUES (183,'Callie','Battle Girl');
INSERT INTO GROUP07."Trainer" VALUES (184,'Jennifer','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (185,'Jenna','Pokémon Ranger');
INSERT INTO GROUP07."Trainer" VALUES (186,'Lorenzo','Pokémon Ranger');
INSERT INTO GROUP07."Trainer" VALUES (187,'Jeffrey','Bug Maniac');
INSERT INTO GROUP07."Trainer" VALUES (188,'Keigo','Ninja Boy');
INSERT INTO GROUP07."Trainer" VALUES (189,'Chip','Ruin Maniac');
INSERT INTO GROUP07."Trainer" VALUES (190,'Cale','Bug Maniac');
INSERT INTO GROUP07."Trainer" VALUES (191,'Tammy','Hex Maniac');
INSERT INTO GROUP07."Trainer" VALUES (192,'Jessica','Beauty');
INSERT INTO GROUP07."Trainer" VALUES (193,'Kate & Joy','Sr. and Jr.');
INSERT INTO GROUP07."Trainer" VALUES (194,'Pat','Pokémon Breeder');
INSERT INTO GROUP07."Trainer" VALUES (195,'Myles','Pokémon Breeder');
INSERT INTO GROUP07."Trainer" VALUES (196,'Walter','Gentleman');
INSERT INTO GROUP07."Trainer" VALUES (197,'Vanessa','Pokéfan');
INSERT INTO GROUP07."Trainer" VALUES (198,'Marcel','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (199,'Cristin','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (200,'Davis','Bug Catcher');
INSERT INTO GROUP07."Trainer" VALUES (201,'Jazmyn','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (202,'Violet','Aroma Lady');
INSERT INTO GROUP07."Trainer" VALUES (203,'Miu & Yuki','Twins');
INSERT INTO GROUP07."Trainer" VALUES (204,'Kindra','Hex Maniac');
INSERT INTO GROUP07."Trainer" VALUES (205,'Ed','Collector');
INSERT INTO GROUP07."Trainer" VALUES (206,'Wendy','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (207,'Braxton','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (208,'Fernando','Guitarist');
INSERT INTO GROUP07."Trainer" VALUES (209,'Alberto','Bird Keeper');
INSERT INTO GROUP07."Trainer" VALUES (210,'Jacki','Psychic');
INSERT INTO GROUP07."Trainer" VALUES (211,'Fredrick','Expert');
INSERT INTO GROUP07."Trainer" VALUES (212,'Cameron','Psychic');
INSERT INTO GROUP07."Trainer" VALUES (213,'Jonas','Ninja Boy');
INSERT INTO GROUP07."Trainer" VALUES (214,'Kayley','Parasol Lady');
INSERT INTO GROUP07."Trainer" VALUES (215,'Grace','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (216,'Declan','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (217,'Lila & Roy','Sis and Bro');
INSERT INTO GROUP07."Trainer" VALUES (218,'Spencer','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (219,'Jenny','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (220,'Chad','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (221,'Isabella','Triathlete');
INSERT INTO GROUP07."Trainer" VALUES (222,'Roland','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (223,'Ernest','Sailor');
INSERT INTO GROUP07."Trainer" VALUES (224,'Nolen','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (225,'Sharon','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (226,'Tanya','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (227,'Presley','Bird Keeper');
INSERT INTO GROUP07."Trainer" VALUES (228,'Auron','Expert');
INSERT INTO GROUP07."Trainer" VALUES (229,'Stan','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (230,'Kim & Iris','Sr. and Jr.');
INSERT INTO GROUP07."Trainer" VALUES (231,'Leonardo','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (232,'Isobel','Triathlete');
INSERT INTO GROUP07."Trainer" VALUES (233,'Dean','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (234,'Nikki','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (235,'Barry','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (236,'Sienna','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (237,'Pablo','Triathlete');
INSERT INTO GROUP07."Trainer" VALUES (238,'Brenda','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (239,'Aidan','Bird Keeper');
INSERT INTO GROUP07."Trainer" VALUES (240,'Athena','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (241,'Jonah','Fisherman');
INSERT INTO GROUP07."Trainer" VALUES (242,'Roger','Fisherman');
INSERT INTO GROUP07."Trainer" VALUES (243,'Henry','Fisherman');
INSERT INTO GROUP07."Trainer" VALUES (244,'Camden','Triathlete');
INSERT INTO GROUP07."Trainer" VALUES (245,'Koji','Black Belt');
INSERT INTO GROUP07."Trainer" VALUES (246,'Donny','Triathlete');
INSERT INTO GROUP07."Trainer" VALUES (247,'Ruben','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (248,'Alexa','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (249,'Wayne','Fisherman');
INSERT INTO GROUP07."Trainer" VALUES (250,'Isaiah','Triathlete');
INSERT INTO GROUP07."Trainer" VALUES (251,'Katelyn','Triathlete');
INSERT INTO GROUP07."Trainer" VALUES (252,'Carlee','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (253,'Harrison','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (254,'Reed','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (255,'Chase','Triathlete');
INSERT INTO GROUP07."Trainer" VALUES (256,'Allison','Triathlete');
INSERT INTO GROUP07."Trainer" VALUES (257,'Clarence','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (258,'Tisha','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (259,'Rodney','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (260,'Katie','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (261,'Santiago','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (262,'Kevin','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (263,'Taila','Triathlete');
INSERT INTO GROUP07."Trainer" VALUES (264,'Richard','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (265,'Kara','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (266,'Herman','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (267,'Susie','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (268,'Reli & Ian','Sis and Bro');
INSERT INTO GROUP07."Trainer" VALUES (269,'Gilbert','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (270,'Dana','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (271,'Ronald','Fisherman');
INSERT INTO GROUP07."Trainer" VALUES (272,'Kiyo','Black Belt');
INSERT INTO GROUP07."Trainer" VALUES (273,'Paxton','Expert');
INSERT INTO GROUP07."Trainer" VALUES (274,'Darcy','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (275,'Makayla','Expert');
INSERT INTO GROUP07."Trainer" VALUES (276,'Jonathan','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (277,'Linda','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (278,'Beck','Bird Keeper');
INSERT INTO GROUP07."Trainer" VALUES (279,'Conor','Expert');
INSERT INTO GROUP07."Trainer" VALUES (280,'Mollie','Expert');
INSERT INTO GROUP07."Trainer" VALUES (281,'Warren','Cool Trainer');
INSERT INTO GROUP07."Trainer" VALUES (282,'Debra','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (283,'Franklin','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (284,'Laurel','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (285,'Jack','Swimmer');
INSERT INTO GROUP07."Trainer" VALUES (286,'Hitoshi','Black Belt');
INSERT INTO GROUP07."Trainer" VALUES (287,'Reyna','Battle Girl');
INSERT INTO GROUP07."Trainer" VALUES (288,'Hudson','Sailor');
INSERT INTO GROUP07."Trainer" VALUES (289,'Aaron','Dragon Tamer');
INSERT INTO GROUP07."Trainer" VALUES (290,'Marley','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (291,'Alex','Bird Keeper');
INSERT INTO GROUP07."Trainer" VALUES (292,'Kelvin','Sailor');
INSERT INTO GROUP07."Trainer" VALUES (293,'Eric','Hiker');
INSERT INTO GROUP07."Trainer" VALUES (294,'NULL','Team Magma Grunt');
INSERT INTO GROUP07."Trainer" VALUES (295,'Diana','Picnicker');
INSERT INTO GROUP07."Trainer" VALUES (296,'Autumn','Picnicker');
INSERT INTO GROUP07."Trainer" VALUES (297,'Julio','Triathlete');
INSERT INTO GROUP07."Trainer" VALUES (298,'Ethan','Camper');
INSERT INTO GROUP07."Trainer" VALUES (299,'Tabitha','Magma Admin');
INSERT INTO GROUP07."Trainer" VALUES (300,'Maxie','Magma Leader');
INSERT INTO GROUP07."Trainer" VALUES (301,'Wally','Pokémon Trainer');
INSERT INTO GROUP07."Trainer" VALUES (302,'John and Jay','Old Couple');
INSERT INTO GROUP07."Trainer" VALUES (303,'Nicolas','Dragon Tamer');
INSERT INTO GROUP07."Trainer" VALUES (304,'Steven','Pokémon Trainer');
INSERT INTO GROUP07."Trainer" VALUES (305,'Shirley','Beauty');
INSERT INTO GROUP07."Trainer" VALUES (306,'Sheila','Beauty');
INSERT INTO GROUP07."Trainer" VALUES (307,'Shelby','Expert');
INSERT INTO GROUP07."Trainer" VALUES (308,'Sawyer','Hiker');
INSERT INTO GROUP07."Trainer" VALUES (309,'Melissa','Beauty');
INSERT INTO GROUP07."Trainer" VALUES (310,'Mark','PokéManiac');
INSERT INTO GROUP07."Trainer" VALUES (311,'Leah','Hex Maniac');
INSERT INTO GROUP07."Trainer" VALUES (312,'Zander','Black Belt');
INSERT INTO GROUP07."Trainer" VALUES (313,'Dez & Luke','Young Couple');
INSERT INTO GROUP07."Trainer" VALUES (314,'Kayla','Psychic');
INSERT INTO GROUP07."Trainer" VALUES (315,'Gabrielle','Pokémon Breeder');
INSERT INTO GROUP07."Trainer" VALUES (316,'William','Psychic');
INSERT INTO GROUP07."Trainer" VALUES (317,'Tasha','Hex Maniac');
INSERT INTO GROUP07."Trainer" VALUES (318,'Atsushi','Black Belt');
INSERT INTO GROUP07."Trainer" VALUES (319,'Valerie','Hex Maniac');
INSERT INTO GROUP07."Trainer" VALUES (320,'Cedric','Psychic');
INSERT INTO GROUP07."Trainer" VALUES (321,'NULL','Team Aqua Grunt');
INSERT INTO GROUP07."Trainer" VALUES (322,'Lyle','Bug Catcher');
INSERT INTO GROUP07."Trainer" VALUES (323,'James','Bug Catcher');
INSERT INTO GROUP07."Trainer" VALUES (326,'Mike','Hiker');
INSERT INTO GROUP07."Trainer" VALUES (327,'Lea & Jed','Young Couple');
INSERT INTO GROUP07."Trainer" VALUES (328,'Garret','Rich Boy');
INSERT INTO GROUP07."Trainer" VALUES (329,'Tucker','Gentleman');
INSERT INTO GROUP07."Trainer" VALUES (330,'Colton','Pokéfan');
INSERT INTO GROUP07."Trainer" VALUES (331,'Anette','Lady');
INSERT INTO GROUP07."Trainer" VALUES (332,'Thomas','Gentleman');
INSERT INTO GROUP07."Trainer" VALUES (333,'Phillip','Sailor');
INSERT INTO GROUP07."Trainer" VALUES (334,'Leonard','Sailor');
INSERT INTO GROUP07."Trainer" VALUES (335,'Shelly','Aqua Admin');
INSERT INTO GROUP07."Trainer" VALUES (336,'Archie','Aqua Leader');
INSERT INTO GROUP07."Trainer" VALUES (337,'Jaclyn','Psychic');
INSERT INTO GROUP07."Trainer" VALUES (338,'Abigail','Triathlete');
INSERT INTO GROUP07."Trainer" VALUES (339,'Anthony','Triathlete');
INSERT INTO GROUP07."Trainer" VALUES (340,'Benjamin','Triathlete');
INSERT INTO GROUP07."Trainer" VALUES (341,'Jasmine','Triathlete');
INSERT INTO GROUP07."Trainer" VALUES (342,'Jacob','Triathlete');
INSERT INTO GROUP07."Trainer" VALUES (343,'Matt','Aqua Admin');
INSERT INTO GROUP07."Trainer" VALUES (344,'Shigenobu','Youngster');
INSERT INTO GROUP07."Trainer" VALUES (345,'Akari','Parasol Lady');
INSERT INTO GROUP07."Trainer" VALUES (346,'Shigezo','Ninja Boy');
INSERT INTO GROUP07."Trainer" VALUES (347,'Namiko','Beauty');
INSERT INTO GROUP07."Trainer" VALUES (348,'Makie','Hex Maniac');
INSERT INTO GROUP07."Trainer" VALUES (349,'Haruhito','Camper');
INSERT INTO GROUP07."Trainer" VALUES (350,'Meiko','School Kid');
INSERT INTO GROUP07."Trainer" VALUES (351,'Pierre','Gentleman');
INSERT INTO GROUP07."Trainer" VALUES (352,'Alfonso','Triathlete');
INSERT INTO GROUP07."Trainer" VALUES (353,'Alaina','Hex Maniac');
INSERT INTO GROUP07."Trainer" VALUES (354,'Theodore','Black Belt');
INSERT INTO GROUP07."Trainer" VALUES (355,'Jayden','Pokémon Breeder');
INSERT INTO GROUP07."Trainer" VALUES (356,'Salvadore','Pokémon Breeder');
INSERT INTO GROUP07."Trainer" VALUES (357,'Veronica','Pokémon Breeder');
INSERT INTO GROUP07."Trainer" VALUES (358,'Keenan','Psychic');
INSERT INTO GROUP07."Trainer" VALUES (359,'Kristina','Aroma Lady');
INSERT INTO GROUP07."Trainer" VALUES (360,'Terrance','Gentleman');
INSERT INTO GROUP07."Trainer" VALUES (361,'Elizabeth','Lady');
INSERT INTO GROUP07."Trainer" VALUES (362,'Annabell','Parasol Lady');
INSERT INTO GROUP07."Trainer" VALUES (363,'Coleman','Collector');
INSERT INTO GROUP07."Trainer" VALUES (364,'Enrique','Rich Boy');
INSERT INTO GROUP07."Trainer" VALUES (365,'Colleen','Lady');
INSERT INTO GROUP07."Trainer" VALUES (366,'Kimberly','Pokéfan');
INSERT INTO GROUP07."Trainer" VALUES (367,'Francisco','Pokéfan');
INSERT INTO GROUP07."Trainer" VALUES (368,'Bernard','Kindler');
INSERT INTO GROUP07."Trainer" VALUES (369,'Merdith','Pokémon Ranger');
INSERT INTO GROUP07."Trainer" VALUES (370,'Abraham','Ruin Maniac');
INSERT INTO GROUP07."Trainer" VALUES (371,'Luc','Tuber');
INSERT INTO GROUP07."Trainer" VALUES (372,'Breyden','Youngster');
INSERT INTO GROUP07."Trainer" VALUES (373,'Aniya','Tuber');
INSERT INTO GROUP07."Trainer" VALUES (374,'Dane','Bird Keeper');
INSERT INTO GROUP07."Trainer" VALUES (375,'Stephanie','Triathlete');
INSERT INTO GROUP07."Trainer" VALUES (376,'Alfred','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (377,'Edie','Psychic');
INSERT INTO GROUP07."Trainer" VALUES (378,'Roderick','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (379,'Alicia','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (380,'Terrence','Expert');
INSERT INTO GROUP07."Trainer" VALUES (381,'Carlotta','Expert');
INSERT INTO GROUP07."Trainer" VALUES (382,'Nora','Pokémon Ranger');
INSERT INTO GROUP07."Trainer" VALUES (383,'Gav','Pokémon Ranger');
INSERT INTO GROUP07."Trainer" VALUES (384,'Sally','Lass');
INSERT INTO GROUP07."Trainer" VALUES (385,'Robin','Lass');
INSERT INTO GROUP07."Trainer" VALUES (386,'Eddie','Youngster');
INSERT INTO GROUP07."Trainer" VALUES (387,'Ted','School Kid');
INSERT INTO GROUP07."Trainer" VALUES (388,'Paul','School Kid');
INSERT INTO GROUP07."Trainer" VALUES (389,'Georgia','School Kid');
INSERT INTO GROUP07."Trainer" VALUES (390,'Justin','Camper');
INSERT INTO GROUP07."Trainer" VALUES (391,'Martha','Picnicker');
INSERT INTO GROUP07."Trainer" VALUES (392,'Alan','Hiker');
INSERT INTO GROUP07."Trainer" VALUES (393,'Yuji','Black Belt');
INSERT INTO GROUP07."Trainer" VALUES (394,'Cora','Battle Girl');
INSERT INTO GROUP07."Trainer" VALUES (395,'Jill','Battle Girl');
INSERT INTO GROUP07."Trainer" VALUES (396,'Sophia','Pokémon Ranger');
INSERT INTO GROUP07."Trainer" VALUES (397,'Sebastian','Pokémon Ranger');
INSERT INTO GROUP07."Trainer" VALUES (398,'Benny','Bird Keeper');
INSERT INTO GROUP07."Trainer" VALUES (399,'Joshua','Psychic');
INSERT INTO GROUP07."Trainer" VALUES (400,'Patricia','Hex Maniac');
INSERT INTO GROUP07."Trainer" VALUES (401,'Mariella','Psychic');
INSERT INTO GROUP07."Trainer" VALUES (402,'Everett','Gentleman');
INSERT INTO GROUP07."Trainer" VALUES (403,'Alexis','Psychic');
INSERT INTO GROUP07."Trainer" VALUES (404,'Alvaro','Psychic');
INSERT INTO GROUP07."Trainer" VALUES (405,'Elaine','Cool Trainer');
INSERT INTO GROUP07."Trainer" VALUES (406,'Vincent','Cool Trainer');
INSERT INTO GROUP07."Trainer" VALUES (407,'Leroy','Cool Trainer');
INSERT INTO GROUP07."Trainer" VALUES (408,'Albert','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (409,'Hope','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (410,'Shannon','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (411,'Samuel','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (412,'Julie','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (413,'Owen','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (414,'Dianne','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (415,'Felix','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (416,'Caroline','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (417,'Vito','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (418,'Michelle','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (419,'Mitchell','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (420,'Halle','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (421,'Edgar','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (422,'Katelynn','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (423,'Quincy','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (424,'Josh','Youngster');
INSERT INTO GROUP07."Trainer" VALUES (425,'Tommy','Youngster');
INSERT INTO GROUP07."Trainer" VALUES (426,'Marc','Hiker');
INSERT INTO GROUP07."Trainer" VALUES (427,'Roxanne','Leader');
INSERT INTO GROUP07."Trainer" VALUES (428,'Laura','Battle Girl');
INSERT INTO GROUP07."Trainer" VALUES (429,'Lilith','Battle Girl');
INSERT INTO GROUP07."Trainer" VALUES (430,'Brenden','Sailor');
INSERT INTO GROUP07."Trainer" VALUES (431,'Takao','Black Belt');
INSERT INTO GROUP07."Trainer" VALUES (432,'Christian','Black Belt');
INSERT INTO GROUP07."Trainer" VALUES (433,'Jocelyn','Battle Girl');
INSERT INTO GROUP07."Trainer" VALUES (434,'Brawly','Leader');
INSERT INTO GROUP07."Trainer" VALUES (435,'Vivian','Battle Girl');
INSERT INTO GROUP07."Trainer" VALUES (436,'Kirk','Guitarist');
INSERT INTO GROUP07."Trainer" VALUES (437,'Ben','Youngster');
INSERT INTO GROUP07."Trainer" VALUES (438,'Angelo','Bug Maniac');
INSERT INTO GROUP07."Trainer" VALUES (439,'Shawn','Guitarist');
INSERT INTO GROUP07."Trainer" VALUES (440,'Wattson','Leader');
INSERT INTO GROUP07."Trainer" VALUES (441,'Jeff','Kindler');
INSERT INTO GROUP07."Trainer" VALUES (442,'Jace','Kindler');
INSERT INTO GROUP07."Trainer" VALUES (443,'Eli','Hiker');
INSERT INTO GROUP07."Trainer" VALUES (444,'Cole','Kindler');
INSERT INTO GROUP07."Trainer" VALUES (445,'Gerald','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (446,'Axle','Kindler');
INSERT INTO GROUP07."Trainer" VALUES (447,'Keegan','Kindler');
INSERT INTO GROUP07."Trainer" VALUES (448,'Danielle','Battle Girl');
INSERT INTO GROUP07."Trainer" VALUES (449,'Flannery','Leader');
INSERT INTO GROUP07."Trainer" VALUES (450,'Randall','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (451,'Mary','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (452,'Parker','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (453,'Alexia','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (454,'George','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (455,'Jody','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (456,'Berke','Cooltrainer');
INSERT INTO GROUP07."Trainer" VALUES (457,'Norman','Leader');
INSERT INTO GROUP07."Trainer" VALUES (458,'Humberto','Bird Keeper');
INSERT INTO GROUP07."Trainer" VALUES (459,'Jared','Bird Keeper');
INSERT INTO GROUP07."Trainer" VALUES (460,'Ashley','Picnicker');
INSERT INTO GROUP07."Trainer" VALUES (461,'Flint','Camper');
INSERT INTO GROUP07."Trainer" VALUES (462,'Edwardo','Bird Keeper');
INSERT INTO GROUP07."Trainer" VALUES (463,'Darius','Bird Keeper');
INSERT INTO GROUP07."Trainer" VALUES (464,'Winona','Leader');
INSERT INTO GROUP07."Trainer" VALUES (465,'Preston','Psychic');
INSERT INTO GROUP07."Trainer" VALUES (466,'Maura','Psychic');
INSERT INTO GROUP07."Trainer" VALUES (467,'Samantha','Psychic');
INSERT INTO GROUP07."Trainer" VALUES (468,'Blake','Psychic');
INSERT INTO GROUP07."Trainer" VALUES (469,'Macey','Psychic');
INSERT INTO GROUP07."Trainer" VALUES (470,'Clifford','Gentleman');
INSERT INTO GROUP07."Trainer" VALUES (471,'Kathleen','Hex Maniac');
INSERT INTO GROUP07."Trainer" VALUES (472,'Nicholas','Psychic');
INSERT INTO GROUP07."Trainer" VALUES (473,'Nate','Gentleman');
INSERT INTO GROUP07."Trainer" VALUES (474,'Virgil','Psychic');
INSERT INTO GROUP07."Trainer" VALUES (475,'Sylvia','Hex Maniac');
INSERT INTO GROUP07."Trainer" VALUES (476,'Hannah','Psychic');
INSERT INTO GROUP07."Trainer" VALUES (477,'Tate & Liza','Leader');
INSERT INTO GROUP07."Trainer" VALUES (478,'Connie','Beauty');
INSERT INTO GROUP07."Trainer" VALUES (479,'Andrea','Lass');
INSERT INTO GROUP07."Trainer" VALUES (480,'Daphne','Lady');
INSERT INTO GROUP07."Trainer" VALUES (481,'Annika','Pokéfan');
INSERT INTO GROUP07."Trainer" VALUES (482,'Tiffany','Beauty');
INSERT INTO GROUP07."Trainer" VALUES (483,'Crissy','Lass');
INSERT INTO GROUP07."Trainer" VALUES (484,'Bethany','Pokéfan');
INSERT INTO GROUP07."Trainer" VALUES (485,'Olivia','Beauty');
INSERT INTO GROUP07."Trainer" VALUES (486,'Brianna','Lady');
INSERT INTO GROUP07."Trainer" VALUES (487,'Bridget','Beauty');
INSERT INTO GROUP07."Trainer" VALUES (488,'Juan','Leader');
INSERT INTO GROUP07."Trainer" VALUES (489,'Billy','Youngster');
INSERT INTO GROUP07."Trainer" VALUES (490,'Darian','Fisherman');
INSERT INTO GROUP07."Trainer" VALUES (491,'Cindy','Lady');
INSERT INTO GROUP07."Trainer" VALUES (492,'Winston','Rich Boy');
INSERT INTO GROUP07."Trainer" VALUES (493,'Haley','Lass');
INSERT INTO GROUP07."Trainer" VALUES (494,'Gina & Mia','Twins');
INSERT INTO GROUP07."Trainer" VALUES (495,'Ivan','Fisherman');
