create table Move
(
    MoveName char(16) not null
        primary key,
    Accuracy integer,
    Power    integer,
    PP       integer,
    Status   smallint,
    TypeName char(8)
        references Type
);

INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Absorb', 100, 20, 20, 0, 'Grass');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Acid Armor', null, 0, 40, 1, 'Poison');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Acid', 100, 40, 30, 0, 'Poison');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Aerial Ace', null, 60, 20, 0, 'Flying');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Aeroblast', 95, 100, 5, 0, 'Flying');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Agility', null, 0, 30, 1, 'Psychic');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Air Cutter', 95, 55, 25, 0, 'Flying');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Amnesia', null, 0, 20, 1, 'Psychic');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Ancient Power', 100, 60, 5, 0, 'Rock');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Arm Thrust', 100, 15, 20, 0, 'Fighting');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Aromatherapy', null, 0, 5, 1, 'Grass');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Assist', null, 0, 20, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Astonish', 100, 30, 15, 0, 'Ghost');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Attract', 100, 0, 15, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Aurora Beam', 100, 65, 20, 0, 'Ice');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Barrage', 85, 15, 20, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Barrier', null, 0, 30, 1, 'Psychic');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Baton Pass', null, 0, 40, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Beat Up', 100, 10, 10, 0, 'Dark');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Belly Drum', null, 0, 10, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Bide', 100, 0, 10, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Bind', 75, 15, 20, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Bite', 100, 60, 25, 0, 'Dark');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Blast Burn', 90, 150, 5, 0, 'Fire');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Blaze Kick', 90, 85, 10, 0, 'Fire');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Blizzard', 70, 120, 5, 0, 'Ice');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Block', null, 0, 5, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Body Slam', 100, 85, 15, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Bone Club', 85, 65, 20, 0, 'Ground');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Bone Rush', 80, 25, 10, 0, 'Ground');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Bonemerang', 90, 50, 10, 0, 'Ground');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Bounce', 85, 85, 5, 0, 'Flying');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Brick Break', 100, 75, 15, 0, 'Fighting');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Bubble Beam', 100, 65, 20, 0, 'Water');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Bubble', 100, 20, 30, 0, 'Water');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Bulk Up', null, 0, 20, 1, 'Fighting');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Bullet Seed', 100, 10, 30, 0, 'Grass');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Calm Mind', null, 0, 20, 1, 'Psychic');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Camouflage', null, 0, 20, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Charge', null, 0, 20, 1, 'Electric');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Charm', 100, 0, 20, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Clamp', 75, 35, 10, 0, 'Water');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Comet Punch', 85, 18, 15, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Confuse Ray', 100, 0, 10, 1, 'Ghost');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Confusion', 100, 50, 25, 0, 'Psychic');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Constrict', 100, 10, 35, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Conversion 2', null, 0, 30, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Conversion', null, 0, 30, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Cosmic Power', null, 0, 20, 1, 'Psychic');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Cotton Spore', 85, 0, 40, 1, 'Grass');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Counter', 100, 0, 20, 0, 'Fighting');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Covet', 100, 40, 40, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Crabhammer', 85, 90, 10, 0, 'Water');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Cross Chop', 80, 100, 5, 0, 'Fighting');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Crunch', 100, 80, 15, 0, 'Dark');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Crush Claw', 95, 75, 10, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Curse', null, 0, 10, 1, '???');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Cut', 95, 50, 30, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Defense Curl', null, 0, 40, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Destiny Bond', null, 0, 5, 1, 'Ghost');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Detect', null, 0, 5, 1, 'Fighting');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Dig', 100, 60, 10, 0, 'Ground');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Disable', 55, 0, 20, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Dive', 100, 60, 10, 0, 'Water');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Dizzy Punch', 100, 70, 10, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Doom Desire', 85, 120, 5, 0, 'Steel');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Double Kick', 100, 30, 30, 0, 'Fighting');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Double Slap', 85, 15, 10, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Double Team', null, 0, 15, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Double-Edge', 100, 120, 15, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Dragon Breath', 100, 60, 20, 0, 'Dragon');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Dragon Claw', 100, 80, 15, 0, 'Dragon');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Dragon Dance', null, 0, 20, 1, 'Dragon');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Dragon Rage', 100, 0, 10, 0, 'Dragon');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Dream Eater', 100, 100, 15, 0, 'Psychic');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Drill Peck', 100, 80, 20, 0, 'Flying');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Dynamic Punch', 50, 100, 5, 0, 'Fighting');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Earthquake', 100, 100, 10, 0, 'Ground');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Egg Bomb', 75, 100, 10, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Ember', 100, 40, 25, 0, 'Fire');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Encore', 100, 0, 5, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Endeavor', 100, 0, 5, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Endure', null, 0, 10, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Eruption', 100, 150, 5, 0, 'Fire');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Explosion', 100, 250, 5, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Extrasensory', 100, 80, 30, 0, 'Psychic');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Extreme Speed', 100, 80, 5, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Facade', 100, 70, 20, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Fake Out', 100, 40, 10, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Fake Tears', 100, 0, 20, 1, 'Dark');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('False Swipe', 100, 40, 40, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Feather Dance', 100, 0, 15, 1, 'Flying');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Feint Attack', null, 60, 20, 0, 'Dark');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Fire Blast', 85, 120, 5, 0, 'Fire');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Fire Punch', 100, 75, 15, 0, 'Fire');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Fire Spin', 70, 15, 15, 0, 'Fire');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Fissure', 30, 0, 5, 1, 'Ground');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Flail', 100, 0, 15, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Flame Wheel', 100, 60, 25, 0, 'Fire');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Flamethrower', 100, 95, 15, 0, 'Fire');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Flash', 70, 0, 20, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Flatter', 100, 0, 15, 1, 'Dark');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Fly', 95, 70, 15, 0, 'Flying');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Focus Energy', null, 0, 30, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Focus Punch', 100, 150, 20, 0, 'Fighting');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Follow Me', null, 0, 20, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Foresight', 100, 0, 40, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Frenzy Plant', 90, 150, 5, 0, 'Grass');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Frustration', 100, 0, 20, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Fury Attack', 85, 15, 20, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Fury Cutter', 95, 10, 20, 0, 'Bug');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Fury Swipes', 80, 18, 15, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Future Sight', 90, 80, 15, 0, 'Psychic');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Giga Drain', 100, 60, 5, 0, 'Grass');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Glare', 75, 0, 30, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Grass Whistle', 55, 0, 15, 1, 'Grass');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Growl', 100, 0, 40, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Growth', null, 0, 40, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Grudge', null, 0, 5, 1, 'Ghost');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Guillotine', 30, 0, 5, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Gust', 100, 40, 35, 0, 'Flying');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Hail', null, 0, 10, 1, 'Ice');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Harden', null, 0, 30, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Haze', null, 0, 30, 1, 'Ice');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Headbutt', 100, 70, 15, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Heal Bell', null, 0, 5, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Heat Wave', 90, 100, 10, 0, 'Fire');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Helping Hand', null, 0, 20, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Hidden Power', 100, 0, 15, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('High Jump Kick', 90, 85, 20, 0, 'Fighting');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Horn Attack', 100, 65, 25, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Horn Drill', 30, 0, 5, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Howl', null, 0, 40, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Hydro Cannon', 90, 150, 5, 0, 'Water');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Hydro Pump', 80, 120, 5, 0, 'Water');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Hyper Beam', 90, 150, 5, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Hyper Fang', 90, 80, 15, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Hyper Voice', 100, 90, 10, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Hypnosis', 60, 0, 20, 1, 'Psychic');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Ice Ball', 90, 30, 20, 0, 'Ice');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Ice Beam', 100, 95, 10, 0, 'Ice');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Ice Punch', 100, 75, 15, 0, 'Ice');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Icicle Spear', 100, 10, 30, 0, 'Ice');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Icy Wind', 95, 55, 15, 0, 'Ice');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Imprison', null, 0, 10, 1, 'Psychic');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Ingrain', null, 0, 20, 1, 'Grass');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Iron Defense', null, 0, 15, 1, 'Steel');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Iron Tail', 75, 100, 15, 0, 'Steel');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Jump Kick', 95, 70, 25, 0, 'Fighting');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Karate Chop', 100, 50, 25, 0, 'Fighting');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Kinesis', 80, 0, 15, 1, 'Psychic');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Knock Off', 100, 20, 20, 0, 'Dark');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Leaf Blade', 100, 70, 15, 0, 'Grass');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Leech Life', 100, 20, 15, 0, 'Bug');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Leech Seed', 90, 0, 10, 1, 'Grass');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Leer', 100, 0, 30, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Lick', 100, 20, 30, 0, 'Ghost');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Light Screen', null, 0, 30, 1, 'Psychic');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Lock-On', 100, 0, 5, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Lovely Kiss', 75, 0, 10, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Low Kick', 100, 0, 20, 0, 'Fighting');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Luster Purge', 100, 70, 5, 0, 'Psychic');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Mach Punch', 100, 40, 30, 0, 'Fighting');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Magic Coat', null, 0, 15, 1, 'Psychic');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Magical Leaf', null, 60, 20, 0, 'Grass');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Magnitude', 100, 0, 30, 0, 'Ground');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Mean Look', null, 0, 5, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Meditate', null, 0, 40, 1, 'Psychic');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Mega Drain', 100, 40, 10, 0, 'Grass');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Mega Kick', 75, 120, 5, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Mega Punch', 85, 80, 20, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Megahorn', 85, 120, 10, 0, 'Bug');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Memento', 100, 0, 10, 1, 'Dark');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Metal Claw', 95, 50, 35, 0, 'Steel');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Metal Sound', 85, 0, 40, 1, 'Steel');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Meteor Mash', 85, 100, 10, 0, 'Steel');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Metronome', null, 0, 10, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Milk Drink', null, 0, 10, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Mimic', null, 0, 10, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Mind Reader', 100, 0, 5, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Minimize', null, 0, 20, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Mirror Coat', 100, 0, 20, 0, 'Psychic');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Mirror Move', null, 0, 20, 1, 'Flying');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Mist Ball', 100, 70, 5, 0, 'Psychic');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Mist', null, 0, 30, 1, 'Ice');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Moonlight', null, 0, 5, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Morning Sun', null, 0, 5, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Mud Shot', 95, 55, 15, 0, 'Ground');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Mud Sport', null, 0, 15, 1, 'Ground');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Mud-Slap', 100, 20, 10, 0, 'Ground');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Muddy Water', 85, 95, 10, 0, 'Water');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Nature Power', null, 0, 20, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Needle Arm', 100, 60, 15, 0, 'Grass');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Night Shade', 100, 0, 15, 0, 'Ghost');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Nightmare', 100, 0, 15, 1, 'Ghost');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Octazooka', 85, 65, 10, 0, 'Water');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Odor Sleuth', 100, 0, 40, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Outrage', 100, 90, 15, 0, 'Dragon');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Overheat', 90, 140, 5, 0, 'Fire');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Pain Split', null, 0, 20, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Pay Day', 100, 40, 20, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Peck', 100, 35, 35, 0, 'Flying');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Perish Song', null, 0, 5, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Petal Dance', 100, 70, 20, 0, 'Grass');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Pin Missile', 85, 14, 20, 0, 'Bug');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Poison Fang', 100, 50, 15, 0, 'Poison');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Poison Gas', 55, 0, 40, 1, 'Poison');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Poison Powder', 75, 0, 35, 1, 'Poison');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Poison Sting', 100, 15, 35, 0, 'Poison');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Poison Tail', 100, 50, 25, 0, 'Poison');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Pound', 100, 40, 35, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Powder Snow', 100, 40, 25, 0, 'Ice');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Present', 90, 0, 15, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Protect', null, 0, 10, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Psybeam', 100, 65, 20, 0, 'Psychic');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Psych Up', null, 0, 10, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Psychic', 100, 90, 10, 0, 'Psychic');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Psycho Boost', 90, 140, 5, 0, 'Psychic');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Psywave', 80, 0, 15, 0, 'Psychic');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Pursuit', 100, 40, 20, 0, 'Dark');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Quick Attack', 100, 40, 30, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Rage', 100, 20, 20, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Rain Dance', null, 0, 5, 1, 'Water');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Rapid Spin', 100, 20, 40, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Razor Leaf', 95, 55, 25, 0, 'Grass');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Razor Wind', 100, 80, 10, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Recover', null, 0, 20, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Recycle', null, 0, 10, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Reflect', null, 0, 20, 1, 'Psychic');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Refresh', null, 0, 20, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Rest', null, 0, 10, 1, 'Psychic');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Return', 100, 0, 20, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Revenge', 100, 60, 10, 0, 'Fighting');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Reversal', 100, 0, 15, 0, 'Fighting');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Roar', 100, 0, 20, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Rock Blast', 80, 25, 10, 0, 'Rock');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Rock Slide', 90, 75, 10, 0, 'Rock');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Rock Smash', 100, 20, 15, 0, 'Fighting');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Rock Throw', 90, 50, 15, 0, 'Rock');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Rock Tomb', 80, 50, 10, 0, 'Rock');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Role Play', null, 0, 10, 1, 'Psychic');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Rolling Kick', 85, 60, 15, 0, 'Fighting');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Rollout', 90, 30, 20, 0, 'Rock');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Sacred Fire', 95, 100, 5, 0, 'Fire');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Safeguard', null, 0, 25, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Sand Attack', 100, 0, 15, 1, 'Ground');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Sand Tomb', 70, 15, 15, 0, 'Ground');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Sandstorm', null, 0, 10, 1, 'Rock');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Scary Face', 90, 0, 10, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Scratch', 100, 40, 35, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Screech', 85, 0, 40, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Secret Power', 100, 70, 20, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Seismic Toss', 100, 0, 20, 0, 'Fighting');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Self-Destruct', 100, 200, 5, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Shadow Ball', 100, 80, 15, 0, 'Ghost');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Shadow Punch', null, 60, 20, 0, 'Ghost');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Sharpen', null, 0, 30, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Sheer Cold', 30, 0, 5, 1, 'Ice');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Shock Wave', null, 60, 20, 0, 'Electric');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Signal Beam', 100, 75, 15, 0, 'Bug');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Silver Wind', 100, 60, 5, 0, 'Bug');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Sing', 55, 0, 15, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Sketch', null, 0, 1, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Skill Swap', null, 0, 10, 1, 'Psychic');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Skull Bash', 100, 100, 15, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Sky Attack', 90, 140, 5, 0, 'Flying');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Sky Uppercut', 90, 85, 15, 0, 'Fighting');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Slack Off', null, 0, 10, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Slam', 75, 80, 20, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Slash', 100, 70, 20, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Sleep Powder', 75, 0, 15, 1, 'Grass');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Sleep Talk', null, 0, 10, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Sludge Bomb', 100, 90, 10, 0, 'Poison');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Sludge', 100, 65, 20, 0, 'Poison');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Smelling Salts', 100, 60, 10, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Smog', 70, 20, 20, 0, 'Poison');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Smokescreen', 100, 0, 20, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Snatch', null, 0, 10, 1, 'Dark');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Snore', 100, 40, 15, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Soft-Boiled', null, 0, 10, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Solar Beam', 100, 120, 10, 0, 'Grass');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Sonic Boom', 90, 0, 20, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Spark', 100, 65, 20, 0, 'Electric');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Spider Web', null, 0, 10, 1, 'Bug');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Spike Cannon', 100, 20, 15, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Spikes', null, 0, 20, 1, 'Ground');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Spit Up', 100, 0, 10, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Spite', 100, 0, 10, 1, 'Ghost');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Splash', null, 0, 40, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Spore', 100, 0, 15, 1, 'Grass');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Steel Wing', 90, 70, 25, 0, 'Steel');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Stockpile', null, 0, 10, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Stomp', 100, 65, 20, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Strength', 100, 80, 15, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('String Shot', 95, 0, 40, 1, 'Bug');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Struggle', 100, 50, 1, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Stun Spore', 75, 0, 30, 1, 'Grass');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Submission', 80, 80, 25, 0, 'Fighting');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Substitute', null, 0, 10, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Sunny Day', null, 0, 5, 1, 'Fire');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Super Fang', 90, 0, 10, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Superpower', 100, 120, 5, 0, 'Fighting');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Supersonic', 55, 0, 20, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Surf', 100, 95, 15, 0, 'Water');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Swagger', 90, 0, 15, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Swallow', null, 0, 10, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Sweet Kiss', 75, 0, 10, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Sweet Scent', 100, 0, 20, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Swift', null, 60, 20, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Swords Dance', null, 0, 30, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Synthesis', null, 0, 5, 1, 'Grass');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Tackle', 95, 35, 35, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Tail Glow', null, 0, 20, 1, 'Bug');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Tail Whip', 100, 0, 30, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Take Down', 85, 90, 20, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Taunt', 100, 0, 20, 1, 'Dark');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Teeter Dance', 100, 0, 20, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Teleport', null, 0, 20, 1, 'Psychic');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Thief', 100, 40, 10, 0, 'Dark');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Thrash', 100, 90, 20, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Thunder Punch', 100, 75, 15, 0, 'Electric');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Thunder Shock', 100, 40, 30, 0, 'Electric');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Thunder Wave', 100, 0, 20, 1, 'Electric');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Thunder', 70, 120, 10, 0, 'Electric');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Thunderbolt', 100, 95, 15, 0, 'Electric');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Tickle', 100, 0, 20, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Torment', 100, 0, 15, 1, 'Dark');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Toxic', 85, 0, 10, 1, 'Poison');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Transform', null, 0, 10, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Tri Attack', 100, 80, 10, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Trick', 100, 0, 10, 1, 'Psychic');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Triple Kick', 90, 10, 10, 0, 'Fighting');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Twineedle', 100, 25, 20, 0, 'Bug');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Twister', 100, 40, 20, 0, 'Dragon');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Uproar', 100, 50, 10, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Vine Whip', 100, 35, 10, 0, 'Grass');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Vise Grip', 100, 55, 30, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Vital Throw', null, 70, 10, 0, 'Fighting');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Volt Tackle', 100, 120, 15, 0, 'Electric');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Water Gun', 100, 40, 25, 0, 'Water');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Water Pulse', 100, 60, 20, 0, 'Water');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Water Sport', null, 0, 15, 1, 'Water');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Water Spout', 100, 150, 5, 0, 'Water');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Waterfall', 100, 80, 15, 0, 'Water');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Weather Ball', 100, 50, 10, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Whirlpool', 70, 15, 15, 0, 'Water');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Whirlwind', 100, 0, 20, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Will-O-Wisp', 75, 0, 15, 1, 'Fire');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Wing Attack', 100, 60, 35, 0, 'Flying');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Wish', null, 0, 10, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Withdraw', null, 0, 40, 1, 'Water');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Wrap', 85, 15, 20, 0, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Yawn', null, 0, 10, 1, 'Normal');
INSERT INTO Move (MoveName, Accuracy, Power, PP, Status, TypeName) VALUES ('Zap Cannon', 50, 100, 5, 0, 'Electric');