create table Abilities
(
    Dex     integer  not null
        references Pokemon
            on delete cascade,
    Ability char(16) not null,
    primary key (Dex, Ability),
    check ("Dex" > 0)
);

INSERT INTO Abilities (Dex, Ability) VALUES (1, 'Overgrow');
INSERT INTO Abilities (Dex, Ability) VALUES (10, 'Shield Dust');
INSERT INTO Abilities (Dex, Ability) VALUES (100, 'Soundproof');
INSERT INTO Abilities (Dex, Ability) VALUES (100, 'Static');
INSERT INTO Abilities (Dex, Ability) VALUES (101, 'Soundproof');
INSERT INTO Abilities (Dex, Ability) VALUES (101, 'Static');
INSERT INTO Abilities (Dex, Ability) VALUES (102, 'Chlorophyll');
INSERT INTO Abilities (Dex, Ability) VALUES (103, 'Chlorophyll');
INSERT INTO Abilities (Dex, Ability) VALUES (104, 'Lightning Rod');
INSERT INTO Abilities (Dex, Ability) VALUES (104, 'Rock Head');
INSERT INTO Abilities (Dex, Ability) VALUES (105, 'Lightning Rod');
INSERT INTO Abilities (Dex, Ability) VALUES (105, 'Rock Head');
INSERT INTO Abilities (Dex, Ability) VALUES (106, 'Limber');
INSERT INTO Abilities (Dex, Ability) VALUES (106, 'Reckless');
INSERT INTO Abilities (Dex, Ability) VALUES (107, 'Iron Fist');
INSERT INTO Abilities (Dex, Ability) VALUES (107, 'Keen Eye');
INSERT INTO Abilities (Dex, Ability) VALUES (108, 'Oblivious');
INSERT INTO Abilities (Dex, Ability) VALUES (108, 'Own Tempo');
INSERT INTO Abilities (Dex, Ability) VALUES (109, 'Levitate');
INSERT INTO Abilities (Dex, Ability) VALUES (109, 'Neutralizing Gas');
INSERT INTO Abilities (Dex, Ability) VALUES (11, 'Shed Skin');
INSERT INTO Abilities (Dex, Ability) VALUES (110, 'Levitate');
INSERT INTO Abilities (Dex, Ability) VALUES (110, 'Neutralizing Gas');
INSERT INTO Abilities (Dex, Ability) VALUES (111, 'Lightning Rod');
INSERT INTO Abilities (Dex, Ability) VALUES (111, 'Rock Head');
INSERT INTO Abilities (Dex, Ability) VALUES (112, 'Lightning Rod');
INSERT INTO Abilities (Dex, Ability) VALUES (112, 'Rock Head');
INSERT INTO Abilities (Dex, Ability) VALUES (113, 'Natural Cure');
INSERT INTO Abilities (Dex, Ability) VALUES (113, 'Serene Grace');
INSERT INTO Abilities (Dex, Ability) VALUES (114, 'Chlorophyll');
INSERT INTO Abilities (Dex, Ability) VALUES (114, 'Leaf Guard');
INSERT INTO Abilities (Dex, Ability) VALUES (115, 'Early Bird');
INSERT INTO Abilities (Dex, Ability) VALUES (115, 'Scrappy');
INSERT INTO Abilities (Dex, Ability) VALUES (116, 'Sniper');
INSERT INTO Abilities (Dex, Ability) VALUES (116, 'Swift Swim');
INSERT INTO Abilities (Dex, Ability) VALUES (117, 'Poison Point');
INSERT INTO Abilities (Dex, Ability) VALUES (117, 'Sniper');
INSERT INTO Abilities (Dex, Ability) VALUES (118, 'Swift Swim');
INSERT INTO Abilities (Dex, Ability) VALUES (118, 'Water Veil');
INSERT INTO Abilities (Dex, Ability) VALUES (119, 'Swift Swim');
INSERT INTO Abilities (Dex, Ability) VALUES (119, 'Water Veil');
INSERT INTO Abilities (Dex, Ability) VALUES (12, 'Compound Eyes');
INSERT INTO Abilities (Dex, Ability) VALUES (120, 'Illuminate');
INSERT INTO Abilities (Dex, Ability) VALUES (120, 'Natural Cure');
INSERT INTO Abilities (Dex, Ability) VALUES (121, 'Illuminate');
INSERT INTO Abilities (Dex, Ability) VALUES (121, 'Natural Cure');
INSERT INTO Abilities (Dex, Ability) VALUES (122, 'Filter');
INSERT INTO Abilities (Dex, Ability) VALUES (122, 'Soundproof');
INSERT INTO Abilities (Dex, Ability) VALUES (123, 'Swarm');
INSERT INTO Abilities (Dex, Ability) VALUES (123, 'Technician');
INSERT INTO Abilities (Dex, Ability) VALUES (124, 'Forewarn');
INSERT INTO Abilities (Dex, Ability) VALUES (124, 'Oblivious');
INSERT INTO Abilities (Dex, Ability) VALUES (125, 'Static');
INSERT INTO Abilities (Dex, Ability) VALUES (126, 'Flame Body');
INSERT INTO Abilities (Dex, Ability) VALUES (127, 'Hyper Cutter');
INSERT INTO Abilities (Dex, Ability) VALUES (127, 'Mold Breaker');
INSERT INTO Abilities (Dex, Ability) VALUES (128, 'Anger Point');
INSERT INTO Abilities (Dex, Ability) VALUES (128, 'Intimidate');
INSERT INTO Abilities (Dex, Ability) VALUES (129, 'Swift Swim');
INSERT INTO Abilities (Dex, Ability) VALUES (13, 'Shield Dust');
INSERT INTO Abilities (Dex, Ability) VALUES (130, 'Intimidate');
INSERT INTO Abilities (Dex, Ability) VALUES (131, 'Shell Armor');
INSERT INTO Abilities (Dex, Ability) VALUES (131, 'Water Absorb');
INSERT INTO Abilities (Dex, Ability) VALUES (132, 'Limber');
INSERT INTO Abilities (Dex, Ability) VALUES (133, 'Adaptability');
INSERT INTO Abilities (Dex, Ability) VALUES (133, 'Run Away');
INSERT INTO Abilities (Dex, Ability) VALUES (134, 'Water Absorb');
INSERT INTO Abilities (Dex, Ability) VALUES (135, 'Volt Absorb');
INSERT INTO Abilities (Dex, Ability) VALUES (136, 'Flash Fire');
INSERT INTO Abilities (Dex, Ability) VALUES (137, 'Download');
INSERT INTO Abilities (Dex, Ability) VALUES (137, 'Trace');
INSERT INTO Abilities (Dex, Ability) VALUES (138, 'Shell Armor');
INSERT INTO Abilities (Dex, Ability) VALUES (138, 'Swift Swim');
INSERT INTO Abilities (Dex, Ability) VALUES (139, 'Shell Armor');
INSERT INTO Abilities (Dex, Ability) VALUES (139, 'Swift Swim');
INSERT INTO Abilities (Dex, Ability) VALUES (14, 'Shed Skin');
INSERT INTO Abilities (Dex, Ability) VALUES (140, 'Battle Armor');
INSERT INTO Abilities (Dex, Ability) VALUES (140, 'Swift Swim');
INSERT INTO Abilities (Dex, Ability) VALUES (141, 'Battle Armor');
INSERT INTO Abilities (Dex, Ability) VALUES (141, 'Swift Swim');
INSERT INTO Abilities (Dex, Ability) VALUES (142, 'Pressure');
INSERT INTO Abilities (Dex, Ability) VALUES (142, 'Rock Head');
INSERT INTO Abilities (Dex, Ability) VALUES (143, 'Immunity');
INSERT INTO Abilities (Dex, Ability) VALUES (143, 'Thick Fat');
INSERT INTO Abilities (Dex, Ability) VALUES (144, 'Pressure');
INSERT INTO Abilities (Dex, Ability) VALUES (145, 'Pressure');
INSERT INTO Abilities (Dex, Ability) VALUES (146, 'Pressure');
INSERT INTO Abilities (Dex, Ability) VALUES (147, 'Shed Skin');
INSERT INTO Abilities (Dex, Ability) VALUES (148, 'Shed Skin');
INSERT INTO Abilities (Dex, Ability) VALUES (149, 'Inner Focus');
INSERT INTO Abilities (Dex, Ability) VALUES (15, 'Swarm');
INSERT INTO Abilities (Dex, Ability) VALUES (150, 'Pressure');
INSERT INTO Abilities (Dex, Ability) VALUES (151, 'Synchronize');
INSERT INTO Abilities (Dex, Ability) VALUES (152, 'Overgrow');
INSERT INTO Abilities (Dex, Ability) VALUES (153, 'Overgrow');
INSERT INTO Abilities (Dex, Ability) VALUES (154, 'Overgrow');
INSERT INTO Abilities (Dex, Ability) VALUES (155, 'Blaze');
INSERT INTO Abilities (Dex, Ability) VALUES (156, 'Blaze');
INSERT INTO Abilities (Dex, Ability) VALUES (157, 'Blaze');
INSERT INTO Abilities (Dex, Ability) VALUES (158, 'Torrent');
INSERT INTO Abilities (Dex, Ability) VALUES (159, 'Torrent');
INSERT INTO Abilities (Dex, Ability) VALUES (16, 'Keen Eye');
INSERT INTO Abilities (Dex, Ability) VALUES (16, 'Tangled Feet');
INSERT INTO Abilities (Dex, Ability) VALUES (160, 'Torrent');
INSERT INTO Abilities (Dex, Ability) VALUES (161, 'Keen Eye');
INSERT INTO Abilities (Dex, Ability) VALUES (161, 'Run Away');
INSERT INTO Abilities (Dex, Ability) VALUES (162, 'Keen Eye');
INSERT INTO Abilities (Dex, Ability) VALUES (162, 'Run Away');
INSERT INTO Abilities (Dex, Ability) VALUES (163, 'Insomnia');
INSERT INTO Abilities (Dex, Ability) VALUES (163, 'Keen Eye');
INSERT INTO Abilities (Dex, Ability) VALUES (164, 'Insomnia');
INSERT INTO Abilities (Dex, Ability) VALUES (164, 'Keen Eye');
INSERT INTO Abilities (Dex, Ability) VALUES (165, 'Early Bird');
INSERT INTO Abilities (Dex, Ability) VALUES (165, 'Swarm');
INSERT INTO Abilities (Dex, Ability) VALUES (166, 'Early Bird');
INSERT INTO Abilities (Dex, Ability) VALUES (166, 'Swarm');
INSERT INTO Abilities (Dex, Ability) VALUES (167, 'Insomnia');
INSERT INTO Abilities (Dex, Ability) VALUES (167, 'Swarm');
INSERT INTO Abilities (Dex, Ability) VALUES (168, 'Insomnia');
INSERT INTO Abilities (Dex, Ability) VALUES (168, 'Swarm');
INSERT INTO Abilities (Dex, Ability) VALUES (169, 'Inner Focus');
INSERT INTO Abilities (Dex, Ability) VALUES (17, 'Keen Eye');
INSERT INTO Abilities (Dex, Ability) VALUES (17, 'Tangled Feet');
INSERT INTO Abilities (Dex, Ability) VALUES (170, 'Illuminate');
INSERT INTO Abilities (Dex, Ability) VALUES (170, 'Volt Absorb');
INSERT INTO Abilities (Dex, Ability) VALUES (171, 'Illuminate');
INSERT INTO Abilities (Dex, Ability) VALUES (171, 'Volt Absorb');
INSERT INTO Abilities (Dex, Ability) VALUES (172, 'Static');
INSERT INTO Abilities (Dex, Ability) VALUES (173, 'Cute Charm');
INSERT INTO Abilities (Dex, Ability) VALUES (173, 'Magic Guard');
INSERT INTO Abilities (Dex, Ability) VALUES (174, 'Competitive');
INSERT INTO Abilities (Dex, Ability) VALUES (174, 'Cute Charm');
INSERT INTO Abilities (Dex, Ability) VALUES (175, 'Hustle');
INSERT INTO Abilities (Dex, Ability) VALUES (175, 'Serene Grace');
INSERT INTO Abilities (Dex, Ability) VALUES (176, 'Hustle');
INSERT INTO Abilities (Dex, Ability) VALUES (176, 'Serene Grace');
INSERT INTO Abilities (Dex, Ability) VALUES (177, 'Early Bird');
INSERT INTO Abilities (Dex, Ability) VALUES (177, 'Synchronize');
INSERT INTO Abilities (Dex, Ability) VALUES (178, 'Early Bird');
INSERT INTO Abilities (Dex, Ability) VALUES (178, 'Synchronize');
INSERT INTO Abilities (Dex, Ability) VALUES (179, 'Static');
INSERT INTO Abilities (Dex, Ability) VALUES (18, 'Keen Eye');
INSERT INTO Abilities (Dex, Ability) VALUES (18, 'Tangled Feet');
INSERT INTO Abilities (Dex, Ability) VALUES (180, 'Static');
INSERT INTO Abilities (Dex, Ability) VALUES (181, 'Static');
INSERT INTO Abilities (Dex, Ability) VALUES (182, 'Chlorophyll');
INSERT INTO Abilities (Dex, Ability) VALUES (183, 'Huge Power');
INSERT INTO Abilities (Dex, Ability) VALUES (183, 'Thick Fat');
INSERT INTO Abilities (Dex, Ability) VALUES (184, 'Huge Power');
INSERT INTO Abilities (Dex, Ability) VALUES (184, 'Thick Fat');
INSERT INTO Abilities (Dex, Ability) VALUES (185, 'Rock Head');
INSERT INTO Abilities (Dex, Ability) VALUES (185, 'Sturdy');
INSERT INTO Abilities (Dex, Ability) VALUES (186, 'Damp');
INSERT INTO Abilities (Dex, Ability) VALUES (186, 'Water Absorb');
INSERT INTO Abilities (Dex, Ability) VALUES (187, 'Chlorophyll');
INSERT INTO Abilities (Dex, Ability) VALUES (187, 'Leaf Guard');
INSERT INTO Abilities (Dex, Ability) VALUES (188, 'Chlorophyll');
INSERT INTO Abilities (Dex, Ability) VALUES (188, 'Leaf Guard');
INSERT INTO Abilities (Dex, Ability) VALUES (189, 'Chlorophyll');
INSERT INTO Abilities (Dex, Ability) VALUES (189, 'Leaf Guard');
INSERT INTO Abilities (Dex, Ability) VALUES (19, 'Guts');
INSERT INTO Abilities (Dex, Ability) VALUES (19, 'Run Away');
INSERT INTO Abilities (Dex, Ability) VALUES (190, 'Pickup');
INSERT INTO Abilities (Dex, Ability) VALUES (190, 'Run Away');
INSERT INTO Abilities (Dex, Ability) VALUES (191, 'Chlorophyll');
INSERT INTO Abilities (Dex, Ability) VALUES (191, 'Solar Power');
INSERT INTO Abilities (Dex, Ability) VALUES (192, 'Chlorophyll');
INSERT INTO Abilities (Dex, Ability) VALUES (192, 'Solar Power');
INSERT INTO Abilities (Dex, Ability) VALUES (193, 'Compound Eyes');
INSERT INTO Abilities (Dex, Ability) VALUES (193, 'Speed Boost');
INSERT INTO Abilities (Dex, Ability) VALUES (194, 'Damp');
INSERT INTO Abilities (Dex, Ability) VALUES (194, 'Water Absorb');
INSERT INTO Abilities (Dex, Ability) VALUES (195, 'Damp');
INSERT INTO Abilities (Dex, Ability) VALUES (195, 'Water Absorb');
INSERT INTO Abilities (Dex, Ability) VALUES (196, 'Synchronize');
INSERT INTO Abilities (Dex, Ability) VALUES (197, 'Synchronize');
INSERT INTO Abilities (Dex, Ability) VALUES (198, 'Insomnia');
INSERT INTO Abilities (Dex, Ability) VALUES (198, 'Super Luck');
INSERT INTO Abilities (Dex, Ability) VALUES (199, 'Oblivious');
INSERT INTO Abilities (Dex, Ability) VALUES (199, 'Own Tempo');
INSERT INTO Abilities (Dex, Ability) VALUES (2, 'Overgrow');
INSERT INTO Abilities (Dex, Ability) VALUES (20, 'Guts');
INSERT INTO Abilities (Dex, Ability) VALUES (20, 'Run Away');
INSERT INTO Abilities (Dex, Ability) VALUES (200, 'Levitate');
INSERT INTO Abilities (Dex, Ability) VALUES (201, 'Levitate');
INSERT INTO Abilities (Dex, Ability) VALUES (202, 'Shadow Tag');
INSERT INTO Abilities (Dex, Ability) VALUES (203, 'Early Bird');
INSERT INTO Abilities (Dex, Ability) VALUES (203, 'Inner Focus');
INSERT INTO Abilities (Dex, Ability) VALUES (204, 'Sturdy');
INSERT INTO Abilities (Dex, Ability) VALUES (205, 'Sturdy');
INSERT INTO Abilities (Dex, Ability) VALUES (206, 'Run Away');
INSERT INTO Abilities (Dex, Ability) VALUES (206, 'Serene Grace');
INSERT INTO Abilities (Dex, Ability) VALUES (207, 'Hyper Cutter');
INSERT INTO Abilities (Dex, Ability) VALUES (207, 'Sand Veil');
INSERT INTO Abilities (Dex, Ability) VALUES (208, 'Rock Head');
INSERT INTO Abilities (Dex, Ability) VALUES (208, 'Sturdy');
INSERT INTO Abilities (Dex, Ability) VALUES (209, 'Intimidate');
INSERT INTO Abilities (Dex, Ability) VALUES (209, 'Run Away');
INSERT INTO Abilities (Dex, Ability) VALUES (21, 'Keen Eye');
INSERT INTO Abilities (Dex, Ability) VALUES (210, 'Intimidate');
INSERT INTO Abilities (Dex, Ability) VALUES (210, 'Quick Feet');
INSERT INTO Abilities (Dex, Ability) VALUES (211, 'Poison Point');
INSERT INTO Abilities (Dex, Ability) VALUES (211, 'Swift Swim');
INSERT INTO Abilities (Dex, Ability) VALUES (212, 'Swarm');
INSERT INTO Abilities (Dex, Ability) VALUES (212, 'Technician');
INSERT INTO Abilities (Dex, Ability) VALUES (213, 'Gluttony');
INSERT INTO Abilities (Dex, Ability) VALUES (213, 'Sturdy');
INSERT INTO Abilities (Dex, Ability) VALUES (214, 'Guts');
INSERT INTO Abilities (Dex, Ability) VALUES (214, 'Swarm');
INSERT INTO Abilities (Dex, Ability) VALUES (215, 'Inner Focus');
INSERT INTO Abilities (Dex, Ability) VALUES (215, 'Keen Eye');
INSERT INTO Abilities (Dex, Ability) VALUES (216, 'Pickup');
INSERT INTO Abilities (Dex, Ability) VALUES (216, 'Quick Feet');
INSERT INTO Abilities (Dex, Ability) VALUES (217, 'Guts');
INSERT INTO Abilities (Dex, Ability) VALUES (217, 'Quick Feet');
INSERT INTO Abilities (Dex, Ability) VALUES (218, 'Flame Body');
INSERT INTO Abilities (Dex, Ability) VALUES (218, 'Magma Armor');
INSERT INTO Abilities (Dex, Ability) VALUES (219, 'Flame Body');
INSERT INTO Abilities (Dex, Ability) VALUES (219, 'Magma Armor');
INSERT INTO Abilities (Dex, Ability) VALUES (22, 'Keen Eye');
INSERT INTO Abilities (Dex, Ability) VALUES (220, 'Oblivious');
INSERT INTO Abilities (Dex, Ability) VALUES (220, 'Snow Cloak');
INSERT INTO Abilities (Dex, Ability) VALUES (221, 'Oblivious');
INSERT INTO Abilities (Dex, Ability) VALUES (221, 'Snow Cloak');
INSERT INTO Abilities (Dex, Ability) VALUES (222, 'Hustle');
INSERT INTO Abilities (Dex, Ability) VALUES (222, 'Natural Cure');
INSERT INTO Abilities (Dex, Ability) VALUES (223, 'Hustle');
INSERT INTO Abilities (Dex, Ability) VALUES (223, 'Sniper');
INSERT INTO Abilities (Dex, Ability) VALUES (224, 'Sniper');
INSERT INTO Abilities (Dex, Ability) VALUES (224, 'Suction Cups');
INSERT INTO Abilities (Dex, Ability) VALUES (225, 'Hustle');
INSERT INTO Abilities (Dex, Ability) VALUES (225, 'Vital Spirit');
INSERT INTO Abilities (Dex, Ability) VALUES (226, 'Swift Swim');
INSERT INTO Abilities (Dex, Ability) VALUES (226, 'Water Absorb');
INSERT INTO Abilities (Dex, Ability) VALUES (227, 'Keen Eye');
INSERT INTO Abilities (Dex, Ability) VALUES (227, 'Sturdy');
INSERT INTO Abilities (Dex, Ability) VALUES (228, 'Early Bird');
INSERT INTO Abilities (Dex, Ability) VALUES (228, 'Flash Fire');
INSERT INTO Abilities (Dex, Ability) VALUES (229, 'Early Bird');
INSERT INTO Abilities (Dex, Ability) VALUES (229, 'Flash Fire');
INSERT INTO Abilities (Dex, Ability) VALUES (23, 'Intimidate');
INSERT INTO Abilities (Dex, Ability) VALUES (23, 'Shed Skin');
INSERT INTO Abilities (Dex, Ability) VALUES (230, 'Sniper');
INSERT INTO Abilities (Dex, Ability) VALUES (230, 'Swift Swim');
INSERT INTO Abilities (Dex, Ability) VALUES (231, 'Pickup');
INSERT INTO Abilities (Dex, Ability) VALUES (232, 'Sturdy');
INSERT INTO Abilities (Dex, Ability) VALUES (233, 'Download');
INSERT INTO Abilities (Dex, Ability) VALUES (233, 'Trace');
INSERT INTO Abilities (Dex, Ability) VALUES (234, 'Frisk');
INSERT INTO Abilities (Dex, Ability) VALUES (234, 'Intimidate');
INSERT INTO Abilities (Dex, Ability) VALUES (235, 'Own Tempo');
INSERT INTO Abilities (Dex, Ability) VALUES (235, 'Technician');
INSERT INTO Abilities (Dex, Ability) VALUES (236, 'Guts');
INSERT INTO Abilities (Dex, Ability) VALUES (236, 'Steadfast');
INSERT INTO Abilities (Dex, Ability) VALUES (237, 'Intimidate');
INSERT INTO Abilities (Dex, Ability) VALUES (237, 'Technician');
INSERT INTO Abilities (Dex, Ability) VALUES (238, 'Forewarn');
INSERT INTO Abilities (Dex, Ability) VALUES (238, 'Oblivious');
INSERT INTO Abilities (Dex, Ability) VALUES (239, 'Static');
INSERT INTO Abilities (Dex, Ability) VALUES (24, 'Intimidate');
INSERT INTO Abilities (Dex, Ability) VALUES (24, 'Shed Skin');
INSERT INTO Abilities (Dex, Ability) VALUES (240, 'Flame Body');
INSERT INTO Abilities (Dex, Ability) VALUES (241, 'Scrappy');
INSERT INTO Abilities (Dex, Ability) VALUES (241, 'Thick Fat');
INSERT INTO Abilities (Dex, Ability) VALUES (242, 'Natural Cure');
INSERT INTO Abilities (Dex, Ability) VALUES (242, 'Serene Grace');
INSERT INTO Abilities (Dex, Ability) VALUES (243, 'Pressure');
INSERT INTO Abilities (Dex, Ability) VALUES (244, 'Pressure');
INSERT INTO Abilities (Dex, Ability) VALUES (245, 'Pressure');
INSERT INTO Abilities (Dex, Ability) VALUES (246, 'Guts');
INSERT INTO Abilities (Dex, Ability) VALUES (247, 'Shed Skin');
INSERT INTO Abilities (Dex, Ability) VALUES (248, 'Sand Stream');
INSERT INTO Abilities (Dex, Ability) VALUES (249, 'Pressure');
INSERT INTO Abilities (Dex, Ability) VALUES (25, 'Static');
INSERT INTO Abilities (Dex, Ability) VALUES (250, 'Pressure');
INSERT INTO Abilities (Dex, Ability) VALUES (251, 'Natural Cure');
INSERT INTO Abilities (Dex, Ability) VALUES (252, 'Overgrow');
INSERT INTO Abilities (Dex, Ability) VALUES (253, 'Overgrow');
INSERT INTO Abilities (Dex, Ability) VALUES (254, 'Overgrow');
INSERT INTO Abilities (Dex, Ability) VALUES (255, 'Blaze');
INSERT INTO Abilities (Dex, Ability) VALUES (256, 'Blaze');
INSERT INTO Abilities (Dex, Ability) VALUES (257, 'Blaze');
INSERT INTO Abilities (Dex, Ability) VALUES (258, 'Torrent');
INSERT INTO Abilities (Dex, Ability) VALUES (259, 'Torrent');
INSERT INTO Abilities (Dex, Ability) VALUES (26, 'Static');
INSERT INTO Abilities (Dex, Ability) VALUES (260, 'Torrent');
INSERT INTO Abilities (Dex, Ability) VALUES (261, 'Quick Feet');
INSERT INTO Abilities (Dex, Ability) VALUES (261, 'Run Away');
INSERT INTO Abilities (Dex, Ability) VALUES (262, 'Intimidate');
INSERT INTO Abilities (Dex, Ability) VALUES (262, 'Quick Feet');
INSERT INTO Abilities (Dex, Ability) VALUES (263, 'Gluttony');
INSERT INTO Abilities (Dex, Ability) VALUES (263, 'Pickup');
INSERT INTO Abilities (Dex, Ability) VALUES (264, 'Gluttony');
INSERT INTO Abilities (Dex, Ability) VALUES (264, 'Pickup');
INSERT INTO Abilities (Dex, Ability) VALUES (265, 'Shield Dust');
INSERT INTO Abilities (Dex, Ability) VALUES (266, 'Shed Skin');
INSERT INTO Abilities (Dex, Ability) VALUES (267, 'Swarm');
INSERT INTO Abilities (Dex, Ability) VALUES (268, 'Shed Skin');
INSERT INTO Abilities (Dex, Ability) VALUES (269, 'Shield Dust');
INSERT INTO Abilities (Dex, Ability) VALUES (27, 'Sand Veil');
INSERT INTO Abilities (Dex, Ability) VALUES (270, 'Rain Dish');
INSERT INTO Abilities (Dex, Ability) VALUES (270, 'Swift Swim');
INSERT INTO Abilities (Dex, Ability) VALUES (271, 'Rain Dish');
INSERT INTO Abilities (Dex, Ability) VALUES (271, 'Swift Swim');
INSERT INTO Abilities (Dex, Ability) VALUES (272, 'Rain Dish');
INSERT INTO Abilities (Dex, Ability) VALUES (272, 'Swift Swim');
INSERT INTO Abilities (Dex, Ability) VALUES (273, 'Chlorophyll');
INSERT INTO Abilities (Dex, Ability) VALUES (273, 'Early Bird');
INSERT INTO Abilities (Dex, Ability) VALUES (274, 'Chlorophyll');
INSERT INTO Abilities (Dex, Ability) VALUES (274, 'Early Bird');
INSERT INTO Abilities (Dex, Ability) VALUES (275, 'Chlorophyll');
INSERT INTO Abilities (Dex, Ability) VALUES (275, 'Early Bird');
INSERT INTO Abilities (Dex, Ability) VALUES (276, 'Guts');
INSERT INTO Abilities (Dex, Ability) VALUES (277, 'Guts');
INSERT INTO Abilities (Dex, Ability) VALUES (278, 'Hydration');
INSERT INTO Abilities (Dex, Ability) VALUES (278, 'Keen Eye');
INSERT INTO Abilities (Dex, Ability) VALUES (279, 'Drizzle');
INSERT INTO Abilities (Dex, Ability) VALUES (279, 'Keen Eye');
INSERT INTO Abilities (Dex, Ability) VALUES (28, 'Sand Veil');
INSERT INTO Abilities (Dex, Ability) VALUES (280, 'Synchronize');
INSERT INTO Abilities (Dex, Ability) VALUES (280, 'Trace');
INSERT INTO Abilities (Dex, Ability) VALUES (281, 'Synchronize');
INSERT INTO Abilities (Dex, Ability) VALUES (281, 'Trace');
INSERT INTO Abilities (Dex, Ability) VALUES (282, 'Synchronize');
INSERT INTO Abilities (Dex, Ability) VALUES (282, 'Trace');
INSERT INTO Abilities (Dex, Ability) VALUES (283, 'Swift Swim');
INSERT INTO Abilities (Dex, Ability) VALUES (284, 'Intimidate');
INSERT INTO Abilities (Dex, Ability) VALUES (285, 'Effect Spore');
INSERT INTO Abilities (Dex, Ability) VALUES (285, 'Poison Heal');
INSERT INTO Abilities (Dex, Ability) VALUES (286, 'Effect Spore');
INSERT INTO Abilities (Dex, Ability) VALUES (286, 'Poison Heal');
INSERT INTO Abilities (Dex, Ability) VALUES (287, 'Truant');
INSERT INTO Abilities (Dex, Ability) VALUES (288, 'Vital Spirit');
INSERT INTO Abilities (Dex, Ability) VALUES (289, 'Truant');
INSERT INTO Abilities (Dex, Ability) VALUES (29, 'Poison Point');
INSERT INTO Abilities (Dex, Ability) VALUES (29, 'Rivalry');
INSERT INTO Abilities (Dex, Ability) VALUES (290, 'Compound Eyes');
INSERT INTO Abilities (Dex, Ability) VALUES (291, 'Speed Boost');
INSERT INTO Abilities (Dex, Ability) VALUES (292, 'Wonder Guard');
INSERT INTO Abilities (Dex, Ability) VALUES (293, 'Soundproof');
INSERT INTO Abilities (Dex, Ability) VALUES (294, 'Soundproof');
INSERT INTO Abilities (Dex, Ability) VALUES (295, 'Soundproof');
INSERT INTO Abilities (Dex, Ability) VALUES (296, 'Guts');
INSERT INTO Abilities (Dex, Ability) VALUES (296, 'Thick Fat');
INSERT INTO Abilities (Dex, Ability) VALUES (297, 'Guts');
INSERT INTO Abilities (Dex, Ability) VALUES (297, 'Thick Fat');
INSERT INTO Abilities (Dex, Ability) VALUES (298, 'Huge Power');
INSERT INTO Abilities (Dex, Ability) VALUES (298, 'Thick Fat');
INSERT INTO Abilities (Dex, Ability) VALUES (299, 'Magnet Pull');
INSERT INTO Abilities (Dex, Ability) VALUES (299, 'Sturdy');
INSERT INTO Abilities (Dex, Ability) VALUES (3, 'Overgrow');
INSERT INTO Abilities (Dex, Ability) VALUES (30, 'Poison Point');
INSERT INTO Abilities (Dex, Ability) VALUES (30, 'Rivalry');
INSERT INTO Abilities (Dex, Ability) VALUES (300, 'Cute Charm');
INSERT INTO Abilities (Dex, Ability) VALUES (300, 'Normalize');
INSERT INTO Abilities (Dex, Ability) VALUES (301, 'Cute Charm');
INSERT INTO Abilities (Dex, Ability) VALUES (301, 'Normalize');
INSERT INTO Abilities (Dex, Ability) VALUES (302, 'Keen Eye');
INSERT INTO Abilities (Dex, Ability) VALUES (302, 'Stall');
INSERT INTO Abilities (Dex, Ability) VALUES (303, 'Hyper Cutter');
INSERT INTO Abilities (Dex, Ability) VALUES (303, 'Intimidate');
INSERT INTO Abilities (Dex, Ability) VALUES (304, 'Rock Head');
INSERT INTO Abilities (Dex, Ability) VALUES (304, 'Sturdy');
INSERT INTO Abilities (Dex, Ability) VALUES (305, 'Rock Head');
INSERT INTO Abilities (Dex, Ability) VALUES (305, 'Sturdy');
INSERT INTO Abilities (Dex, Ability) VALUES (306, 'Rock Head');
INSERT INTO Abilities (Dex, Ability) VALUES (306, 'Sturdy');
INSERT INTO Abilities (Dex, Ability) VALUES (307, 'Pure Power');
INSERT INTO Abilities (Dex, Ability) VALUES (308, 'Pure Power');
INSERT INTO Abilities (Dex, Ability) VALUES (309, 'Lightning Rod');
INSERT INTO Abilities (Dex, Ability) VALUES (309, 'Static');
INSERT INTO Abilities (Dex, Ability) VALUES (31, 'Poison Point');
INSERT INTO Abilities (Dex, Ability) VALUES (31, 'Rivalry');
INSERT INTO Abilities (Dex, Ability) VALUES (310, 'Lightning Rod');
INSERT INTO Abilities (Dex, Ability) VALUES (310, 'Static');
INSERT INTO Abilities (Dex, Ability) VALUES (311, 'Plus');
INSERT INTO Abilities (Dex, Ability) VALUES (312, 'Minus');
INSERT INTO Abilities (Dex, Ability) VALUES (313, 'Illuminate');
INSERT INTO Abilities (Dex, Ability) VALUES (313, 'Swarm');
INSERT INTO Abilities (Dex, Ability) VALUES (314, 'Oblivious');
INSERT INTO Abilities (Dex, Ability) VALUES (314, 'Tinted Lens');
INSERT INTO Abilities (Dex, Ability) VALUES (315, 'Natural Cure');
INSERT INTO Abilities (Dex, Ability) VALUES (315, 'Poison Point');
INSERT INTO Abilities (Dex, Ability) VALUES (316, 'Liquid Ooze');
INSERT INTO Abilities (Dex, Ability) VALUES (316, 'Sticky Hold');
INSERT INTO Abilities (Dex, Ability) VALUES (317, 'Liquid Ooze');
INSERT INTO Abilities (Dex, Ability) VALUES (317, 'Sticky Hold');
INSERT INTO Abilities (Dex, Ability) VALUES (318, 'Rough Skin');
INSERT INTO Abilities (Dex, Ability) VALUES (319, 'Rough Skin');
INSERT INTO Abilities (Dex, Ability) VALUES (32, 'Poison Point');
INSERT INTO Abilities (Dex, Ability) VALUES (32, 'Rivalry');
INSERT INTO Abilities (Dex, Ability) VALUES (320, 'Oblivious');
INSERT INTO Abilities (Dex, Ability) VALUES (320, 'Water Veil');
INSERT INTO Abilities (Dex, Ability) VALUES (321, 'Oblivious');
INSERT INTO Abilities (Dex, Ability) VALUES (321, 'Water Veil');
INSERT INTO Abilities (Dex, Ability) VALUES (322, 'Oblivious');
INSERT INTO Abilities (Dex, Ability) VALUES (322, 'Simple');
INSERT INTO Abilities (Dex, Ability) VALUES (323, 'Magma Armor');
INSERT INTO Abilities (Dex, Ability) VALUES (323, 'Solid Rock');
INSERT INTO Abilities (Dex, Ability) VALUES (324, 'Drought');
INSERT INTO Abilities (Dex, Ability) VALUES (324, 'White Smoke');
INSERT INTO Abilities (Dex, Ability) VALUES (325, 'Own Tempo');
INSERT INTO Abilities (Dex, Ability) VALUES (325, 'Thick Fat');
INSERT INTO Abilities (Dex, Ability) VALUES (326, 'Own Tempo');
INSERT INTO Abilities (Dex, Ability) VALUES (326, 'Thick Fat');
INSERT INTO Abilities (Dex, Ability) VALUES (327, 'Own Tempo');
INSERT INTO Abilities (Dex, Ability) VALUES (327, 'Tangled Feet');
INSERT INTO Abilities (Dex, Ability) VALUES (328, 'Arena Trap');
INSERT INTO Abilities (Dex, Ability) VALUES (328, 'Hyper Cutter');
INSERT INTO Abilities (Dex, Ability) VALUES (329, 'Levitate');
INSERT INTO Abilities (Dex, Ability) VALUES (33, 'Poison Point');
INSERT INTO Abilities (Dex, Ability) VALUES (33, 'Rivalry');
INSERT INTO Abilities (Dex, Ability) VALUES (330, 'Levitate');
INSERT INTO Abilities (Dex, Ability) VALUES (331, 'Sand Veil');
INSERT INTO Abilities (Dex, Ability) VALUES (332, 'Sand Veil');
INSERT INTO Abilities (Dex, Ability) VALUES (333, 'Natural Cure');
INSERT INTO Abilities (Dex, Ability) VALUES (334, 'Natural Cure');
INSERT INTO Abilities (Dex, Ability) VALUES (335, 'Immunity');
INSERT INTO Abilities (Dex, Ability) VALUES (336, 'Shed Skin');
INSERT INTO Abilities (Dex, Ability) VALUES (337, 'Levitate');
INSERT INTO Abilities (Dex, Ability) VALUES (338, 'Levitate');
INSERT INTO Abilities (Dex, Ability) VALUES (339, 'Anticipation');
INSERT INTO Abilities (Dex, Ability) VALUES (339, 'Oblivious');
INSERT INTO Abilities (Dex, Ability) VALUES (34, 'Poison Point');
INSERT INTO Abilities (Dex, Ability) VALUES (34, 'Rivalry');
INSERT INTO Abilities (Dex, Ability) VALUES (340, 'Anticipation');
INSERT INTO Abilities (Dex, Ability) VALUES (340, 'Oblivious');
INSERT INTO Abilities (Dex, Ability) VALUES (341, 'Hyper Cutter');
INSERT INTO Abilities (Dex, Ability) VALUES (341, 'Shell Armor');
INSERT INTO Abilities (Dex, Ability) VALUES (342, 'Hyper Cutter');
INSERT INTO Abilities (Dex, Ability) VALUES (342, 'Shell Armor');
INSERT INTO Abilities (Dex, Ability) VALUES (343, 'Levitate');
INSERT INTO Abilities (Dex, Ability) VALUES (344, 'Levitate');
INSERT INTO Abilities (Dex, Ability) VALUES (345, 'Suction Cups');
INSERT INTO Abilities (Dex, Ability) VALUES (346, 'Suction Cups');
INSERT INTO Abilities (Dex, Ability) VALUES (347, 'Battle Armor');
INSERT INTO Abilities (Dex, Ability) VALUES (348, 'Battle Armor');
INSERT INTO Abilities (Dex, Ability) VALUES (349, 'Oblivious');
INSERT INTO Abilities (Dex, Ability) VALUES (349, 'Swift Swim');
INSERT INTO Abilities (Dex, Ability) VALUES (35, 'Cute Charm');
INSERT INTO Abilities (Dex, Ability) VALUES (35, 'Magic Guard');
INSERT INTO Abilities (Dex, Ability) VALUES (350, 'Competitive');
INSERT INTO Abilities (Dex, Ability) VALUES (350, 'Marvel Scale');
INSERT INTO Abilities (Dex, Ability) VALUES (351, 'Forecast');
INSERT INTO Abilities (Dex, Ability) VALUES (352, 'Color Change');
INSERT INTO Abilities (Dex, Ability) VALUES (353, 'Frisk');
INSERT INTO Abilities (Dex, Ability) VALUES (353, 'Insomnia');
INSERT INTO Abilities (Dex, Ability) VALUES (354, 'Frisk');
INSERT INTO Abilities (Dex, Ability) VALUES (354, 'Insomnia');
INSERT INTO Abilities (Dex, Ability) VALUES (355, 'Levitate');
INSERT INTO Abilities (Dex, Ability) VALUES (356, 'Pressure');
INSERT INTO Abilities (Dex, Ability) VALUES (357, 'Chlorophyll');
INSERT INTO Abilities (Dex, Ability) VALUES (357, 'Solar Power');
INSERT INTO Abilities (Dex, Ability) VALUES (358, 'Levitate');
INSERT INTO Abilities (Dex, Ability) VALUES (359, 'Pressure');
INSERT INTO Abilities (Dex, Ability) VALUES (359, 'Super Luck');
INSERT INTO Abilities (Dex, Ability) VALUES (36, 'Cute Charm');
INSERT INTO Abilities (Dex, Ability) VALUES (36, 'Magic Guard');
INSERT INTO Abilities (Dex, Ability) VALUES (360, 'Shadow Tag');
INSERT INTO Abilities (Dex, Ability) VALUES (361, 'Ice Body');
INSERT INTO Abilities (Dex, Ability) VALUES (361, 'Inner Focus');
INSERT INTO Abilities (Dex, Ability) VALUES (362, 'Ice Body');
INSERT INTO Abilities (Dex, Ability) VALUES (362, 'Inner Focus');
INSERT INTO Abilities (Dex, Ability) VALUES (363, 'Ice Body');
INSERT INTO Abilities (Dex, Ability) VALUES (363, 'Thick Fat');
INSERT INTO Abilities (Dex, Ability) VALUES (364, 'Ice Body');
INSERT INTO Abilities (Dex, Ability) VALUES (364, 'Thick Fat');
INSERT INTO Abilities (Dex, Ability) VALUES (365, 'Ice Body');
INSERT INTO Abilities (Dex, Ability) VALUES (365, 'Thick Fat');
INSERT INTO Abilities (Dex, Ability) VALUES (366, 'Shell Armor');
INSERT INTO Abilities (Dex, Ability) VALUES (367, 'Swift Swim');
INSERT INTO Abilities (Dex, Ability) VALUES (368, 'Swift Swim');
INSERT INTO Abilities (Dex, Ability) VALUES (369, 'Rock Head');
INSERT INTO Abilities (Dex, Ability) VALUES (369, 'Swift Swim');
INSERT INTO Abilities (Dex, Ability) VALUES (37, 'Flash Fire');
INSERT INTO Abilities (Dex, Ability) VALUES (370, 'Swift Swim');
INSERT INTO Abilities (Dex, Ability) VALUES (371, 'Rock Head');
INSERT INTO Abilities (Dex, Ability) VALUES (372, 'Rock Head');
INSERT INTO Abilities (Dex, Ability) VALUES (373, 'Intimidate');
INSERT INTO Abilities (Dex, Ability) VALUES (374, 'Clear Body');
INSERT INTO Abilities (Dex, Ability) VALUES (375, 'Clear Body');
INSERT INTO Abilities (Dex, Ability) VALUES (376, 'Clear Body');
INSERT INTO Abilities (Dex, Ability) VALUES (377, 'Clear Body');
INSERT INTO Abilities (Dex, Ability) VALUES (378, 'Clear Body');
INSERT INTO Abilities (Dex, Ability) VALUES (379, 'Clear Body');
INSERT INTO Abilities (Dex, Ability) VALUES (38, 'Flash Fire');
INSERT INTO Abilities (Dex, Ability) VALUES (380, 'Levitate');
INSERT INTO Abilities (Dex, Ability) VALUES (381, 'Levitate');
INSERT INTO Abilities (Dex, Ability) VALUES (382, 'Drizzle');
INSERT INTO Abilities (Dex, Ability) VALUES (383, 'Drought');
INSERT INTO Abilities (Dex, Ability) VALUES (384, 'Air Lock');
INSERT INTO Abilities (Dex, Ability) VALUES (385, 'Serene Grace');
INSERT INTO Abilities (Dex, Ability) VALUES (386, 'Pressure');
INSERT INTO Abilities (Dex, Ability) VALUES (39, 'Competitive');
INSERT INTO Abilities (Dex, Ability) VALUES (39, 'Cute Charm');
INSERT INTO Abilities (Dex, Ability) VALUES (4, 'Blaze');
INSERT INTO Abilities (Dex, Ability) VALUES (40, 'Competitive');
INSERT INTO Abilities (Dex, Ability) VALUES (40, 'Cute Charm');
INSERT INTO Abilities (Dex, Ability) VALUES (41, 'Inner Focus');
INSERT INTO Abilities (Dex, Ability) VALUES (42, 'Inner Focus');
INSERT INTO Abilities (Dex, Ability) VALUES (43, 'Chlorophyll');
INSERT INTO Abilities (Dex, Ability) VALUES (44, 'Chlorophyll');
INSERT INTO Abilities (Dex, Ability) VALUES (45, 'Chlorophyll');
INSERT INTO Abilities (Dex, Ability) VALUES (46, 'Dry Skin');
INSERT INTO Abilities (Dex, Ability) VALUES (46, 'Effect Spore');
INSERT INTO Abilities (Dex, Ability) VALUES (47, 'Dry Skin');
INSERT INTO Abilities (Dex, Ability) VALUES (47, 'Effect Spore');
INSERT INTO Abilities (Dex, Ability) VALUES (48, 'Compound Eyes');
INSERT INTO Abilities (Dex, Ability) VALUES (48, 'Tinted Lens');
INSERT INTO Abilities (Dex, Ability) VALUES (49, 'Shield Dust');
INSERT INTO Abilities (Dex, Ability) VALUES (49, 'Tinted Lens');
INSERT INTO Abilities (Dex, Ability) VALUES (5, 'Blaze');
INSERT INTO Abilities (Dex, Ability) VALUES (50, 'Arena Trap');
INSERT INTO Abilities (Dex, Ability) VALUES (50, 'Sand Veil');
INSERT INTO Abilities (Dex, Ability) VALUES (51, 'Arena Trap');
INSERT INTO Abilities (Dex, Ability) VALUES (51, 'Sand Veil');
INSERT INTO Abilities (Dex, Ability) VALUES (52, 'Pickup');
INSERT INTO Abilities (Dex, Ability) VALUES (52, 'Technician');
INSERT INTO Abilities (Dex, Ability) VALUES (53, 'Limber');
INSERT INTO Abilities (Dex, Ability) VALUES (53, 'Technician');
INSERT INTO Abilities (Dex, Ability) VALUES (54, 'Cloud Nine');
INSERT INTO Abilities (Dex, Ability) VALUES (54, 'Damp');
INSERT INTO Abilities (Dex, Ability) VALUES (55, 'Cloud Nine');
INSERT INTO Abilities (Dex, Ability) VALUES (55, 'Damp');
INSERT INTO Abilities (Dex, Ability) VALUES (56, 'Anger Point');
INSERT INTO Abilities (Dex, Ability) VALUES (56, 'Vital Spirit');
INSERT INTO Abilities (Dex, Ability) VALUES (57, 'Anger Point');
INSERT INTO Abilities (Dex, Ability) VALUES (57, 'Vital Spirit');
INSERT INTO Abilities (Dex, Ability) VALUES (58, 'Flash Fire');
INSERT INTO Abilities (Dex, Ability) VALUES (58, 'Intimidate');
INSERT INTO Abilities (Dex, Ability) VALUES (59, 'Flash Fire');
INSERT INTO Abilities (Dex, Ability) VALUES (59, 'Intimidate');
INSERT INTO Abilities (Dex, Ability) VALUES (6, 'Blaze');
INSERT INTO Abilities (Dex, Ability) VALUES (60, 'Damp');
INSERT INTO Abilities (Dex, Ability) VALUES (60, 'Water Absorb');
INSERT INTO Abilities (Dex, Ability) VALUES (61, 'Damp');
INSERT INTO Abilities (Dex, Ability) VALUES (61, 'Water Absorb');
INSERT INTO Abilities (Dex, Ability) VALUES (62, 'Damp');
INSERT INTO Abilities (Dex, Ability) VALUES (62, 'Water Absorb');
INSERT INTO Abilities (Dex, Ability) VALUES (63, 'Inner Focus');
INSERT INTO Abilities (Dex, Ability) VALUES (63, 'Synchronize');
INSERT INTO Abilities (Dex, Ability) VALUES (64, 'Inner Focus');
INSERT INTO Abilities (Dex, Ability) VALUES (64, 'Synchronize');
INSERT INTO Abilities (Dex, Ability) VALUES (65, 'Inner Focus');
INSERT INTO Abilities (Dex, Ability) VALUES (65, 'Synchronize');
INSERT INTO Abilities (Dex, Ability) VALUES (66, 'Guts');
INSERT INTO Abilities (Dex, Ability) VALUES (66, 'No Guard');
INSERT INTO Abilities (Dex, Ability) VALUES (67, 'Guts');
INSERT INTO Abilities (Dex, Ability) VALUES (67, 'No Guard');
INSERT INTO Abilities (Dex, Ability) VALUES (68, 'Guts');
INSERT INTO Abilities (Dex, Ability) VALUES (68, 'No Guard');
INSERT INTO Abilities (Dex, Ability) VALUES (69, 'Chlorophyll');
INSERT INTO Abilities (Dex, Ability) VALUES (7, 'Torrent');
INSERT INTO Abilities (Dex, Ability) VALUES (70, 'Chlorophyll');
INSERT INTO Abilities (Dex, Ability) VALUES (71, 'Chlorophyll');
INSERT INTO Abilities (Dex, Ability) VALUES (72, 'Clear Body');
INSERT INTO Abilities (Dex, Ability) VALUES (72, 'Liquid Ooze');
INSERT INTO Abilities (Dex, Ability) VALUES (73, 'Clear Body');
INSERT INTO Abilities (Dex, Ability) VALUES (73, 'Liquid Ooze');
INSERT INTO Abilities (Dex, Ability) VALUES (74, 'Rock Head');
INSERT INTO Abilities (Dex, Ability) VALUES (74, 'Sturdy');
INSERT INTO Abilities (Dex, Ability) VALUES (75, 'Rock Head');
INSERT INTO Abilities (Dex, Ability) VALUES (75, 'Sturdy');
INSERT INTO Abilities (Dex, Ability) VALUES (76, 'Rock Head');
INSERT INTO Abilities (Dex, Ability) VALUES (76, 'Sturdy');
INSERT INTO Abilities (Dex, Ability) VALUES (77, 'Flash Fire');
INSERT INTO Abilities (Dex, Ability) VALUES (77, 'Run Away');
INSERT INTO Abilities (Dex, Ability) VALUES (78, 'Flash Fire');
INSERT INTO Abilities (Dex, Ability) VALUES (78, 'Run Away');
INSERT INTO Abilities (Dex, Ability) VALUES (79, 'Oblivious');
INSERT INTO Abilities (Dex, Ability) VALUES (79, 'Own Tempo');
INSERT INTO Abilities (Dex, Ability) VALUES (8, 'Torrent');
INSERT INTO Abilities (Dex, Ability) VALUES (80, 'Oblivious');
INSERT INTO Abilities (Dex, Ability) VALUES (80, 'Own Tempo');
INSERT INTO Abilities (Dex, Ability) VALUES (81, 'Magnet Pull');
INSERT INTO Abilities (Dex, Ability) VALUES (81, 'Sturdy');
INSERT INTO Abilities (Dex, Ability) VALUES (82, 'Magnet Pull');
INSERT INTO Abilities (Dex, Ability) VALUES (82, 'Sturdy');
INSERT INTO Abilities (Dex, Ability) VALUES (83, 'Inner Focus');
INSERT INTO Abilities (Dex, Ability) VALUES (83, 'Keen Eye');
INSERT INTO Abilities (Dex, Ability) VALUES (84, 'Early Bird');
INSERT INTO Abilities (Dex, Ability) VALUES (84, 'Run Away');
INSERT INTO Abilities (Dex, Ability) VALUES (85, 'Early Bird');
INSERT INTO Abilities (Dex, Ability) VALUES (85, 'Run Away');
INSERT INTO Abilities (Dex, Ability) VALUES (86, 'Hydration');
INSERT INTO Abilities (Dex, Ability) VALUES (86, 'Thick Fat');
INSERT INTO Abilities (Dex, Ability) VALUES (87, 'Hydration');
INSERT INTO Abilities (Dex, Ability) VALUES (87, 'Thick Fat');
INSERT INTO Abilities (Dex, Ability) VALUES (88, 'Stench');
INSERT INTO Abilities (Dex, Ability) VALUES (88, 'Sticky Hold');
INSERT INTO Abilities (Dex, Ability) VALUES (89, 'Stench');
INSERT INTO Abilities (Dex, Ability) VALUES (89, 'Sticky Hold');
INSERT INTO Abilities (Dex, Ability) VALUES (9, 'Torrent');
INSERT INTO Abilities (Dex, Ability) VALUES (90, 'Shell Armor');
INSERT INTO Abilities (Dex, Ability) VALUES (90, 'Skill Link');
INSERT INTO Abilities (Dex, Ability) VALUES (91, 'Shell Armor');
INSERT INTO Abilities (Dex, Ability) VALUES (91, 'Skill Link');
INSERT INTO Abilities (Dex, Ability) VALUES (92, 'Levitate');
INSERT INTO Abilities (Dex, Ability) VALUES (93, 'Levitate');
INSERT INTO Abilities (Dex, Ability) VALUES (94, 'Cursed Body');
INSERT INTO Abilities (Dex, Ability) VALUES (95, 'Rock Head');
INSERT INTO Abilities (Dex, Ability) VALUES (95, 'Sturdy');
INSERT INTO Abilities (Dex, Ability) VALUES (96, 'Forewarn');
INSERT INTO Abilities (Dex, Ability) VALUES (96, 'Insomnia');
INSERT INTO Abilities (Dex, Ability) VALUES (97, 'Forewarn');
INSERT INTO Abilities (Dex, Ability) VALUES (97, 'Insomnia');
INSERT INTO Abilities (Dex, Ability) VALUES (98, 'Hyper Cutter');
INSERT INTO Abilities (Dex, Ability) VALUES (98, 'Shell Armor');
INSERT INTO Abilities (Dex, Ability) VALUES (99, 'Hyper Cutter');
INSERT INTO Abilities (Dex, Ability) VALUES (99, 'Shell Armor');