create table Location
(
    LocationName char(32) not null
        primary key
);

INSERT INTO Location (LocationName) VALUES ('Abandoned Ship');
INSERT INTO Location (LocationName) VALUES ('Altering Cave');
INSERT INTO Location (LocationName) VALUES ('Ancient Tomb');
INSERT INTO Location (LocationName) VALUES ('Artisan Cave');
INSERT INTO Location (LocationName) VALUES ('Battle Arena');
INSERT INTO Location (LocationName) VALUES ('Battle Dome');
INSERT INTO Location (LocationName) VALUES ('Battle Factory');
INSERT INTO Location (LocationName) VALUES ('Battle Frontier');
INSERT INTO Location (LocationName) VALUES ('Battle Palace');
INSERT INTO Location (LocationName) VALUES ('Battle Pike');
INSERT INTO Location (LocationName) VALUES ('Battle Pyramid');
INSERT INTO Location (LocationName) VALUES ('Battle Tower');
INSERT INTO Location (LocationName) VALUES ('Birth Island');
INSERT INTO Location (LocationName) VALUES ('Cave of Origin');
INSERT INTO Location (LocationName) VALUES ('Cove Lily Motel');
INSERT INTO Location (LocationName) VALUES ('Desert Ruins');
INSERT INTO Location (LocationName) VALUES ('Desert Underpass');
INSERT INTO Location (LocationName) VALUES ('Devon Corporation');
INSERT INTO Location (LocationName) VALUES ('Dewford Town');
INSERT INTO Location (LocationName) VALUES ('Ever Grande City');
INSERT INTO Location (LocationName) VALUES ('Fallarbor Town');
INSERT INTO Location (LocationName) VALUES ('Fiery Path');
INSERT INTO Location (LocationName) VALUES ('Fortree City');
INSERT INTO Location (LocationName) VALUES ('Granite Cave');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 101');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 102');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 103');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 104');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 105');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 106');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 107');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 108');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 109');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 110');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 111');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 112');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 113');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 114');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 115');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 116');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 117');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 118');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 119');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 120');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 121');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 122');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 123');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 124');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 125');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 126');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 127');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 128');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 129');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 130');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 131');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 132');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 133');
INSERT INTO Location (LocationName) VALUES ('Hoenn Route 134');
INSERT INTO Location (LocationName) VALUES ('Hoenn Safari Zone');
INSERT INTO Location (LocationName) VALUES ('Island Cave');
INSERT INTO Location (LocationName) VALUES ('Jagged Pass');
INSERT INTO Location (LocationName) VALUES ('Lavaridge Town');
INSERT INTO Location (LocationName) VALUES ('Lilycove City');
INSERT INTO Location (LocationName) VALUES ('Lilycove Department Store');
INSERT INTO Location (LocationName) VALUES ('Lilycove Museum');
INSERT INTO Location (LocationName) VALUES ('Littleroot Town');
INSERT INTO Location (LocationName) VALUES ('Magma Hideout (Jagged Pass)');
INSERT INTO Location (LocationName) VALUES ('Marine Cave');
INSERT INTO Location (LocationName) VALUES ('Mauville City');
INSERT INTO Location (LocationName) VALUES ('Mauville Game Corner');
INSERT INTO Location (LocationName) VALUES ('Meteor Falls');
INSERT INTO Location (LocationName) VALUES ('Mirage Island (Generation III)');
INSERT INTO Location (LocationName) VALUES ('Mirage Tower');
INSERT INTO Location (LocationName) VALUES ('Mossdeep City');
INSERT INTO Location (LocationName) VALUES ('Mossdeep Space Center');
INSERT INTO Location (LocationName) VALUES ('Mt. Chimney');
INSERT INTO Location (LocationName) VALUES ('Mt. Pyre');
INSERT INTO Location (LocationName) VALUES ('New Mauville');
INSERT INTO Location (LocationName) VALUES ('Oceanic Museum');
INSERT INTO Location (LocationName) VALUES ('Oldale Town');
INSERT INTO Location (LocationName) VALUES ('Pacifidlog Town');
INSERT INTO Location (LocationName) VALUES ('Petalburg City');
INSERT INTO Location (LocationName) VALUES ('Petalburg Woods');
INSERT INTO Location (LocationName) VALUES ('Rustboro City');
INSERT INTO Location (LocationName) VALUES ('Rusturf Tunnel');
INSERT INTO Location (LocationName) VALUES ('Rydels Cycles');
INSERT INTO Location (LocationName) VALUES ('S.S. Tidal');
INSERT INTO Location (LocationName) VALUES ('Scorched Slab');
INSERT INTO Location (LocationName) VALUES ('Seafloor Cavern');
INSERT INTO Location (LocationName) VALUES ('Sealed Chamber');
INSERT INTO Location (LocationName) VALUES ('Seaside Cycling Road');
INSERT INTO Location (LocationName) VALUES ('Shoal Cave');
INSERT INTO Location (LocationName) VALUES ('Sky Pillar');
INSERT INTO Location (LocationName) VALUES ('Slateport City');
INSERT INTO Location (LocationName) VALUES ('Sootopolis City');
INSERT INTO Location (LocationName) VALUES ('Southern Island');
INSERT INTO Location (LocationName) VALUES ('Sterns Shipyard');
INSERT INTO Location (LocationName) VALUES ('Submarine Explorer 1');
INSERT INTO Location (LocationName) VALUES ('Team Aqua Hideout');
INSERT INTO Location (LocationName) VALUES ('Terra Cave');
INSERT INTO Location (LocationName) VALUES ('Trainer Hill');
INSERT INTO Location (LocationName) VALUES ('Trick House');
INSERT INTO Location (LocationName) VALUES ('Underwater');
INSERT INTO Location (LocationName) VALUES ('Verdanturf Town');
INSERT INTO Location (LocationName) VALUES ('Victory Road (Hoenn)');
INSERT INTO Location (LocationName) VALUES ('Weather Institute');